In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
encodings_to_try = ['utf-8-sig', 'latin-1', 'ISO-8859-1']

for encoding in encodings_to_try:
    try:
        df = pd.read_csv("C://Users//15694//Desktop//Cross selling//code//Michelle//final_data_with_Loan.csv", encoding=encoding)
        break
    except UnicodeDecodeError:
        continue

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\3053879596.py:5: DtypeWarning: Columns (2,30,31,125) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C://Users//15694//Desktop//Cross selling//code//Michelle//final_data_with_Loan.csv", encoding=encoding)

In [4]:
df=df[[
"CIFNO",
"ACCOUNT_STATUS",
"PRODUCT_DESC",
"SUB_PRODUCT_DESC",
"BAL_OS",
"NET_INTEREST_INCOME",
"REGION_CD",
"CURRENCY_CD",
"ACCOUNT_JOINT",
"DPD_LAST_6_MONTH",
"NPA_FLAG",
"NO_ACCOUNTS_SAVINGS",
"SIX_MONTH_BAL_OS_SAVINGS",
"NO_ACCOUNTS_CURRENT",
"SIX_MONTH_BAL_OS_CURRENT",
"NO_ACCOUNTS_FD",
"SIX_MONTH_BAL_OS_FD",
"NO_ACCOUNTS_HOUSING",
"SIX_MONTH_BAL_OS_HOUSING",
"NO_ACCOUNTS_TERM",
"SIX_MONTH_BAL_OS_TERM",
"NO_ACCOUNTS_LEASING",
"SIX_MONTH_BAL_OS_LEASING",
"NO_ACCOUNTS_PAWNING",
"SIX_MONTH_BAL_OS_PAWNING",
"NO_ACCOUNTS_PERSONAL",
"SIX_MONTH_BAL_OS_PERSONAL",
"NO_ACCOUNTS_SHORT_TERM",  
"SIX_MONTH_BAL_OS_SHORT_TERM",
"NO_ACCOUNTS_STAFF",
"SIX_MONTH_BAL_OS_STAFF",
"NO_ACCOUNTS_TRADE",
"SIX_MONTH_BAL_OS_TRADE",
"NO_ACCOUNTS_DEVELOPMENT",
"SIX_MONTH_BAL_OS_DEVELOPMENT",
"NO_ACCOUNTS_REFINANCE",
"SIX_MONTH_BAL_OS_REFINANCE",
"NO_ACCOUNTS_CARD",
"SIX_MONTH_BAL_OS_CARD",
"NO_ACCOUNTS_OD",
"SIX_MONTH_BAL_OS_OD",
"TOTAL_AVG_BAL",
"FD_AMOUNT_UNDER_LIEN",
"CURRENT_AMOUNT_UNDER_LIEN",
"SAVINGS_AMOUNT_UNDER_LIEN",
"CUSTOMER_PROFITABILITY",
"E_BANKING_ACCOUNTS",
"SOLO_ACCOUNTS",
"DEBIT_CARD_USAGE",
"CREDIT_CARD_USAGE",
"PAYFAST_ACCOUNT",
"NII",'LNAMOUNT']]

In [5]:
df.shape

(1616891, 53)

In [6]:
df.head(5)

,CIFNO,ACCOUNT_STATUS,PRODUCT_DESC,SUB_PRODUCT_DESC,BAL_OS,NET_INTEREST_INCOME,REGION_CD,CURRENCY_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII,LNAMOUNT
0,998101782755,D,Savings,SAVINGS - GENERAL,0.00,0.00,3,LKR,NaN,NaN,NaN,1.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0.00,NaN
1,998101242090,NaN,Savings,SAVINGS MAJOR INVESTMENT,5132.92,14.67,10,LKR,NaN,NaN,Y,3.0,19533.42,1.0,194303.61,NaN,NaN,2.0,7422954.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2174881.48,NaN,NaN,1.0,158714.15,NaN,NaN,9970386.80,NaN,NaN,107407.08,40740.15,1.0,Y,NaN,0.00,NaN,38478.15,NaN
2,998101585644,A,Savings,SAVINGS - FCY,22.93,0.00,1,USD,NaN,NaN,NaN,2.0,5373.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,64745.53,NaN,NaN,70118.75,NaN,NaN,NaN,1319.96,1.0,NaN,NaN,12047.62,NaN,1209.96,NaN
3,998000137604,A,Savings,SAVINGS - MINOR,1042.50,10.75,3,LKR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,10.75,NaN,NaN,NaN,NaN,NaN,10.75,NaN
4,998R00652174,A,Savings,SAVINGS - MINOR,1005.43,8.71,2,LKR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,8.71,NaN,NaN,NaN,NaN,NaN,8.71,NaN

In [7]:
df.isna().sum()

CIFNO                                 0
ACCOUNT_STATUS                    10400
PRODUCT_DESC                          0
SUB_PRODUCT_DESC                      0
BAL_OS                                0
NET_INTEREST_INCOME                   0
REGION_CD                             0
CURRENCY_CD                           0
ACCOUNT_JOINT                   1525757
DPD_LAST_6_MONTH                1599319
NPA_FLAG                        1572609
NO_ACCOUNTS_SAVINGS              338271
SIX_MONTH_BAL_OS_SAVINGS         338069
NO_ACCOUNTS_CURRENT             1499036
SIX_MONTH_BAL_OS_CURRENT        1475250
NO_ACCOUNTS_FD                  1334576
SIX_MONTH_BAL_OS_FD             1321308
NO_ACCOUNTS_HOUSING             1598026
SIX_MONTH_BAL_OS_HOUSING        1597393
NO_ACCOUNTS_TERM                1570966
SIX_MONTH_BAL_OS_TERM           1565388
NO_ACCOUNTS_LEASING             1579955
SIX_MONTH_BAL_OS_LEASING        1576636
NO_ACCOUNTS_PAWNING             1495181
SIX_MONTH_BAL_OS_PAWNING        1495181
NO_ACCOUNTS_PERSONAL            1570393
SIX_MONTH_BAL_OS_PERSONAL       1567782
NO_ACCOUNTS_SHORT_TERM          1610532
SIX_MONTH_BAL_OS_SHORT_TERM     1609491
NO_ACCOUNTS_STAFF               1596672
SIX_MONTH_BAL_OS_STAFF          1596180
NO_ACCOUNTS_TRADE               1613793
SIX_MONTH_BAL_OS_TRADE          1612765
NO_ACCOUNTS_DEVELOPMENT         1584668
SIX_MONTH_BAL_OS_DEVELOPMENT    1581982
NO_ACCOUNTS_REFINANCE           1611033
SIX_MONTH_BAL_OS_REFINANCE      1610292
NO_ACCOUNTS_CARD                1396821
SIX_MONTH_BAL_OS_CARD           1392024
NO_ACCOUNTS_OD                  1580730
SIX_MONTH_BAL_OS_OD             1567956
TOTAL_AVG_BAL                        56
FD_AMOUNT_UNDER_LIEN            1615119
CURRENT_AMOUNT_UNDER_LIEN       1609519
SAVINGS_AMOUNT_UNDER_LIEN       1536845
CUSTOMER_PROFITABILITY               56
E_BANKING_ACCOUNTS              1339628
SOLO_ACCOUNTS                   1421169
DEBIT_CARD_USAGE                1281930
CREDIT_CARD_USAGE               1391340
PAYFAST_ACCOUNT                 1606960
NII                                  56
LNAMOUNT                        1556182
dtype: int64

In [8]:
duplicate_rows = df[df.duplicated()]
duplicate_rows.shape

(8017, 53)

In [9]:
duplicate_rows.head(50)

,CIFNO,ACCOUNT_STATUS,PRODUCT_DESC,SUB_PRODUCT_DESC,BAL_OS,NET_INTEREST_INCOME,REGION_CD,CURRENCY_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII,LNAMOUNT
280,998100899395,R,Time Deposits,TIME DEPOSITS - LKR,1081413.70,144.11,7,LKR,NaN,NaN,NaN,3.0,642836.87,1.0,496293.18,22.0,2.191340e+07,1.0,4319917.38,NaN,NaN,1.0,501730.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,14224.52,NaN,NaN,2.788840e+07,NaN,NaN,NaN,16741.78,1.0,NaN,13000.00,6074.75,NaN,16681.78,5000000.0
3264,998000755529,R,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,10,LKR,NaN,NaN,NaN,1.0,130097.84,NaN,NaN,42.0,5.642506e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,80339.41,NaN,NaN,5.852943e+06,NaN,NaN,NaN,1037.46,1.0,Y,221350.00,43716.03,NaN,657.46,NaN
4669,998000007740,D,Savings,SAVINGS - GENERAL,0.00,0.00,1,LKR,NaN,NaN,Y,310.0,5515467.66,1.0,-968072.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.257729e+07,NaN,NaN,3.0,36525738.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-501189.21,6.314923e+07,NaN,NaN,34.54,934598.69,NaN,NaN,NaN,NaN,NaN,203904.69,NaN
5359,998100490329,R,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,3,LKR,NaN,NaN,NaN,2.0,524001.36,NaN,NaN,11.0,1.010000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,149737.92,NaN,NaN,1.077374e+07,NaN,NaN,NaN,14470.16,NaN,NaN,NaN,42768.39,NaN,14450.16,NaN
5371,998100490329,R,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,3,LKR,NaN,NaN,NaN,2.0,524001.36,NaN,NaN,11.0,1.010000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,149737.92,NaN,NaN,1.077374e+07,NaN,NaN,NaN,14470.16,NaN,NaN,NaN,42768.39,NaN,14450.16,NaN
5373,998100490329,R,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,3,LKR,NaN,NaN,NaN,2.0,524001.36,NaN,NaN,11.0,1.010000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,149737.92,NaN,NaN,1.077374e+07,NaN,NaN,NaN,14470.16,NaN,NaN,NaN,42768.39,NaN,14450.16,NaN
12254,998000084523,A,Loan,HOME LOANS,0.00,0.00,3,LKR,NaN,NaN,Y,2.0,50028.53,NaN,NaN,NaN,NaN,9.0,5366517.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,331281.79,NaN,NaN,5.747828e+06,NaN,NaN,NaN,-50777.91,NaN,NaN,NaN,0.00,NaN,-50777.91,NaN
15092,998000432695,N,Time Deposits,TIME DEPOSITS - LKR,2000000.00,98.28,4,LKR,J,NaN,NaN,4.0,156239.09,NaN,NaN,9.0,1.160000e+07,NaN,NaN,NaN,462978.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,403211.50,NaN,NaN,1.262243e+07,NaN,NaN,NaN,-1656.16,NaN,NaN,NaN,10459.36,NaN,-1806.16,NaN
15815,998001166861,U,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,3,LKR,NaN,NaN,NaN,1.0,46460.96,NaN,NaN,25.0,5.186470e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1415567.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.980676e+06,NaN,NaN,NaN,7871.98,1.0,NaN,36240.50,NaN,NaN,7441.98,2100000.0
17211,998000738030,R,Time Deposits,TIME DEPOSITS - FCY,0.00,837.40,2,USD,NaN,NaN,NaN,8.0,1459317.53,3.0,-1147204.82,13.0,1.844292e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,46953.86,1.0,1809612.51,2.061160e+07,NaN,NaN,43.29,48296.02,1.0,NaN,NaN,45234.49,NaN,45319.02,NaN
18985,998000079292,R,Time Deposits,TIME DEPOSITS - LKR,0.00,8337.44,98,LKR,NaN,NaN,Y,1.0,6453581.44,1.0,1648881.44,30.0,1.000934e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.081959e+08,NaN,NaN,NaN,236189.81,1.0,NaN,NaN,NaN,NaN,235859.81,NaN
25241,998001753864,D,Savings,SAVINGS - GENERAL,0.00,0.00,8,LKR,NaN,NaN,NaN,6.0,270.50,1.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.705000e+02,NaN,NaN,NaN,3.65,1.0,NaN,NaN,NaN,Y,3.65,NaN
26946,998R00303618,U,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,2,LKR,NaN,NaN,NaN,1.0,74564.46,NaN,NaN,5.0,7.494512e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.240157e+05,NaN,NaN,NaN,4602.88,NaN,NaN,0.00,NaN,NaN,4302.88,NaN
27532,998100884263,R,Time Deposits,TIME DEPOSITS - LKR,100000.00,44.48,2,LKR,NaN,NaN,NaN,2.0,27901.63,NaN,NaN,22.0,3.024141e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.052043e+06,NaN,NaN,NaN,2513.69,NaN,NaN,17000.00,NaN,NaN,2392.69,NaN
36125,998101846475,R,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,2,LKR,NaN,NaN,NaN,1.0,189943.50,NaN,NaN,29.0,1.113455e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.303399e+06,NaN,NaN,NaN,2661.07,1.0,NaN,5000.00,NaN,NaN,2631.07,NaN
36134,998000070930,R,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,1,LKR,NaN,NaN,NaN,4.0,153526.78,NaN,NaN,76.0,1.531062e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2077090.54,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3402.11,NaN,NaN,1.754464e+07,NaN,NaN,NaN,2394.80,1.0,Y,33999.00,NaN,NaN,2369.80,NaN
37117,998100047687,A,Current,CURRENT ACCOUNTS,5000.00,66.08,1,LKR,NaN,NaN,NaN,NaN,NaN,63.0,24909738.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.079138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33368.35,2.104081e+09,NaN,NaN,NaN,5774127.90,NaN,NaN,NaN,NaN,NaN,5627629.90,NaN
37314,998100047687,A,Current,CURRENT ACCOUNTS,5000.00,66.08,1,LKR,NaN,NaN,NaN,NaN,NaN,63.0,24909738.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.079138e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33368.35,2.104081e+09,NaN,NaN,NaN,5774127.90,NaN,NaN,NaN,NaN,NaN,5627629.90,NaN
45437,998100182444,A,Loan,TERM LOANS,0.00,0.00,5,LKR,NaN,706.0,Y,2.0,180044.38,1.0,0.00,NaN,NaN,NaN,NaN,8.0,1881178.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.061223e+06,NaN,NaN,NaN,21.03,NaN,NaN,NaN,NaN,NaN,21.03,NaN
46989,998000007740,D,Savings,SAVINGS - GENERAL,0.00,0.00,1,LKR,NaN,NaN,Y,310.0,5515467.66,1.0,-968072.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.257729e+07,NaN,NaN,3.0,36525738.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-501189.21,6.314923e+07,NaN,NaN,34.54,934598.69,NaN,NaN,NaN,NaN,NaN,203904.69,NaN
47637,998001458497,U,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,5,LKR,NaN,NaN,NaN,3.0,255908.30,NaN,NaN,18.0,1.319270e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.344861e+07,NaN,NaN,NaN,3676.24,NaN,NaN,NaN,NaN,NaN,3536.24,NaN
48221,998001324469,N,Time Deposits,TIME DEPOSITS - LKR,1000000.00,0.00,5,LKR,J,NaN,NaN,1.0,290460.43,NaN,NaN,18.0,1.800000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.829046e+07,NaN,NaN,NaN,3298.67,NaN,NaN,NaN,NaN,NaN,3218.67,NaN
48222,998001324469,N,Time Deposits,TIME DEPOSITS - LKR,1000000.00,0.00,5,LKR,J,NaN,NaN,1.0,290460.43,NaN,NaN,18.0,1.800000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.829046e+07,NaN,NaN,NaN,3298.67,NaN,NaN,NaN,NaN,NaN,3218.67,NaN
50437,998001324469,N,Time Deposits,TIME DEPOSITS - LKR,1000000.00,0.00,5,LKR,J,NaN,NaN,1.0,290460.43,NaN,NaN,18.0,1.800000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.829046e+07,NaN,NaN,NaN,3298.67,NaN,NaN,NaN,NaN,NaN,3218.67,NaN
51694,998001458497,U,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,5,LKR,NaN,NaN,NaN,3.0,255908.30,NaN,NaN,18.0,1.319270e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.344861e+07,NaN,NaN,NaN,3676.24,NaN,NaN,NaN,NaN,NaN,3536.24,NaN
52415,998100960504,R,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,1,LKR,NaN,NaN,NaN,3.0,2714404.81,NaN,NaN,5.0,5.715413e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.429818e+06,NaN,NaN,NaN,18117.75,1.0,NaN,NaN,NaN,NaN,18057.75,NaN
53835,998100279500,A,Loan,TERM LOANS,1550595.75,4762.42,10,LKR,NaN,NaN,NaN,NaN,NaN,2.0,982909.06,NaN,NaN,NaN,NaN,11.0,20025490.25,3.0,17351620.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.836002e+07,NaN,NaN,NaN,91633.78,1.0,NaN,NaN,NaN,NaN,91633.78,56900000.0
59150,998100898292,U,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,1,LKR,NaN,NaN,NaN,3.0,70625.25,NaN,NaN,2.0,1.405839e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,995999.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,26263.95,NaN,NaN,1.233473e+06,NaN,NaN,NaN,3392.90,1.0,NaN,132961.46,3030.00,NaN,3142.90,NaN
61179,998000096193,R,Time Deposits,TIME DEPOSITS - FCY,0.00,8746.99,98,USD,NaN,NaN,NaN,2.0,302436.29,NaN,NaN,6.0,1.610977e+07,NaN,NaN,NaN,31769.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.644398e+07,NaN,NaN,NaN,112866.18,1.0,Y,NaN,NaN,NaN,112836.18,5000000.0
61503,998101446565,D,Savings,SAVINGS - GENERAL,0.00,0.00,1,LKR,J,NaN,NaN,56.0,85605.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,895.56,NaN,NaN,8.650113e+04,NaN,NaN,30.00,1598.61,1.0,NaN,125000.00,0.00,NaN,1195.61,NaN
61564,998000007740,D,Savings,SAVINGS - GENERAL,0.00,0.00,1,LKR,NaN,NaN,Y,310.0,5515467.66,1.0,-968072.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.257729e+07,NaN,NaN,3.0,36525738.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-501189.21,6.314923e+07,NaN,NaN,34.54,934598.69,NaN,NaN,NaN,NaN,NaN,203904.69,NaN
61718,998100085625,D,Savings,SAVINGS - OTHERS,0.00,0.00,4,LKR,NaN,NaN,NaN,2.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0.00,NaN
62496,998102166210,N,Time Deposits,TIME DEPOSITS - LKR,2000000.00,0.00,2,LKR,NaN,NaN,NaN,1.0,260078.32,NaN,NaN,6.0,1.300000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,127465.88,NaN,NaN,1.338754e+07,NaN,NaN,NaN,2872.14,NaN,NaN,NaN,224831.67,NaN,2872.14,NaN
63255,998000189611,R,Time Deposits,TIME DEPOSITS - LKR,38424.32,0.00,98,LKR,NaN,NaN,NaN,3.0,350940.00,NaN,0.00,43.0,2.423686e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9010807.85,NaN,NaN,NaN,NaN,NaN,NaN,2.0,374390.13,1.0,133567.01,1.229339e+07,NaN,NaN,NaN,-60285.62,1.0,Y,31900.00,688.00,NaN,-60399.62,NaN
63264,998000086956,R,Time Deposits,TIME DEPOSITS - LKR,79173.19,0.00,98,LKR,NaN,NaN,NaN,5.0,370100.49,NaN,0.00,23.0,2.442005e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2777978.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,496001.10,6.086084e+06,NaN,NaN,NaN,-10202.83,1.0,NaN,61200.00,NaN,NaN,-10404.83,5009000.0
66904,998000070788,R,Time Deposits,TIME DEPOSITS - LKR,0.00,0.00,2,LKR,NaN,NaN,NaN,2.0,2066194.76,2.0,2503929.02,5.0,3.506538e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,80614.45,NaN,NaN,3.971612e+07,NaN,NaN,NaN,28470.28,NaN,NaN,NaN,13419.70,Y,28470.28,NaN
66915,998000738030,R,Time Deposits,TIME DEPOSITS - FCY,0.00,837.40,2,USD,NaN,NaN,NaN,8.0,1459317.53,3.0,-1147204.82,13.0,1.844292e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,46953.86,1.0,1809612.51,2.061160e+07,NaN,NaN,43.29,48296.02,1.0,NaN,NaN,45234.49,NaN,45319.02,NaN
67180,998001920435,D,Savings,SAVINGS - OTHERS,0.00,0.00,6,LKR,NaN,NaN,Y,11.0,10836796.91,NaN,NaN,1.0,4.279878e+06,1.0,41272.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,12461.51,1.517041e+07,NaN,NaN,NaN,150160.73,NaN,NaN,NaN,NaN,NaN,150160.73,NaN
67575,998000313818,R,Time Deposits,TIME DEPOSITS - LKR,920619.99,414.49,1,LKR,J,NaN,NaN,8.0,1503027.20,1.0,10003.65,28.0,5.853853e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,720262.73,NaN,NaN,6.077182e+07,NaN,NaN,NaN,75885.32,NaN,NaN,NaN,25938.68,NaN,75785.32,NaN
69008,998100470924,A,Current,CURRENT ACCOUNTS,0.00,0.00,9,LKR,NaN,NaN,NaN,11.0,4970145.79,16.0,1284545.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.254691e+06,NaN,NaN,NaN,63344.44,NaN,NaN,NaN,NaN,NaN,51258.44,NaN
72184,998000712142,D,Current,CURRENT ACCOUNTS,0.00,0.00,1,LKR,NaN,NaN,NaN,1.0,2222158.76,4.0,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.379597e+08,NaN,NaN,16.0,16632247.85,NaN,NaN,NaN,NaN,NaN,NaN,1.0,20994968.67,1.779091e+08,NaN,NaN,NaN,1071591.83,NaN,NaN,NaN,NaN,NaN,354089.83,NaN
73542,998001147180,D,Savings,SAVINGS - OTHERS,0.00,0.00,4,LKR,NaN,NaN,NaN,2.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0.00,NaN
76618,998000007740,D,Savings,SAVINGS - GENERAL,0.00,0.00,1,LKR,NaN,NaN,Y,310.0,5515467.66,1.0,-968072.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.257729e+07,NaN,NaN,3.0,36525738.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-501189.21,6.314923e+07,NaN,NaN,34.54,934598.69,NaN,NaN,NaN,NaN,NaN,203904.69,NaN
78750,998000007740,D,Savings,SAVINGS - GENERAL,0.00,0.00,1,LKR,NaN,NaN,Y,310.0,5515467.66,1.0,-968072.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.257729e+07,NaN,NaN,3.0,36525738.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-501189.21,6.314923e+07,NaN,NaN,34.54,934598.69,NaN,NaN,NaN,NaN,NaN,203904.69,NaN
79179,998001202599,N,Time Deposits,TIME DEPOSITS - LKR,750000.00,1512.67,10,LKR,NaN,NaN,NaN,3.0,1029973.48,NaN,NaN,2.0,1.500000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.529973e+06,NaN,NaN,NaN,15414.87,NaN,NaN,39000.00,NaN,NaN,15374.87,NaN
80692,998002300142,R,Time Deposits,TIME DEPOSITS - LKR,10000000.00,36354.24,3,LKR,J,NaN,NaN,2.0,307990.40,NaN,NaN,7.0,5.850000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.880799e+07,NaN,NaN,NaN,217240.22,NaN,NaN,NaN,NaN,NaN,217210.22,NaN
80706,998100408475,R,Time Deposits,TIME DEPOSITS - LKR,200000.00,135.83,3,LKR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.473118e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,-180.52,NaN,NaN,4.471313e+05,NaN,NaN,NaN,280.75,NaN,Y,NaN,0.00,NaN,280.75,NaN
81640,998101446565,D,Savings,SAVINGS - GENERAL,0.00,0.00,1,LKR,J,NaN,NaN,56.0,85605.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,895.56,NaN,NaN,8.650113e+04,NaN,NaN,30.00,1598.61,1.0,NaN,125000.00,0.00,NaN,1195.61,NaN
82652,998000313818,R,Time Deposits,TIME DEPOSITS - LKR,920619.99,414.49,1,LKR,J,NaN,NaN,8.0,1503027.20,1.0,10003.65,28.0,5.853853e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,720262.73,NaN,NaN,6.077182e+07,NaN,NaN,NaN,75885.32,NaN,NaN,NaN,25938.68,NaN,75785.32,NaN
83014,998002279621,R,Time Deposits,TIME DEPOSITS - LKR,682342.54,1093.61,7,LKR,NaN,NaN,NaN,1.0,171578.18,NaN,NaN,2.0,3.533801e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.705379e+06,NaN,NaN,NaN,2234.23,NaN,NaN,NaN,NaN,NaN,2234.23,NaN

In [10]:
df=df.drop_duplicates()

In [11]:
df.shape

(1608874, 53)

In [12]:
df = df[~df['SUB_PRODUCT_DESC'].isin(['SAVINGS - MINOR', 'SAVINGS - MINOR - IBU', 'SAVINGS - MINOR - IBU - FC'])]

In [13]:
df = df[df['CURRENCY_CD'] == 'LKR']

In [14]:
df1=df[[
"CIFNO",
"ACCOUNT_STATUS",
"PRODUCT_DESC",
"SUB_PRODUCT_DESC",
"BAL_OS",
"NET_INTEREST_INCOME",
"REGION_CD",
"ACCOUNT_JOINT",
"DPD_LAST_6_MONTH",
"NPA_FLAG",
"NO_ACCOUNTS_SAVINGS",
"SIX_MONTH_BAL_OS_SAVINGS",
"NO_ACCOUNTS_CURRENT",
"SIX_MONTH_BAL_OS_CURRENT",
"NO_ACCOUNTS_FD",
"SIX_MONTH_BAL_OS_FD",
"NO_ACCOUNTS_HOUSING",
"SIX_MONTH_BAL_OS_HOUSING",
"NO_ACCOUNTS_TERM",
"SIX_MONTH_BAL_OS_TERM",
"NO_ACCOUNTS_LEASING",
"SIX_MONTH_BAL_OS_LEASING",
"NO_ACCOUNTS_PAWNING",
"SIX_MONTH_BAL_OS_PAWNING",
"NO_ACCOUNTS_PERSONAL",
"SIX_MONTH_BAL_OS_PERSONAL",
"NO_ACCOUNTS_SHORT_TERM",  
"SIX_MONTH_BAL_OS_SHORT_TERM",
"NO_ACCOUNTS_STAFF",
"SIX_MONTH_BAL_OS_STAFF",
"NO_ACCOUNTS_TRADE",
"SIX_MONTH_BAL_OS_TRADE",
"NO_ACCOUNTS_DEVELOPMENT",
"SIX_MONTH_BAL_OS_DEVELOPMENT",
"NO_ACCOUNTS_REFINANCE",
"SIX_MONTH_BAL_OS_REFINANCE",
"NO_ACCOUNTS_CARD",
"SIX_MONTH_BAL_OS_CARD",
"NO_ACCOUNTS_OD",
"SIX_MONTH_BAL_OS_OD",
"TOTAL_AVG_BAL",
"FD_AMOUNT_UNDER_LIEN",
"CURRENT_AMOUNT_UNDER_LIEN",
"SAVINGS_AMOUNT_UNDER_LIEN",
"CUSTOMER_PROFITABILITY",
"E_BANKING_ACCOUNTS",
"SOLO_ACCOUNTS",
"DEBIT_CARD_USAGE",
"CREDIT_CARD_USAGE",
"PAYFAST_ACCOUNT",
"NII",'LNAMOUNT']]

In [15]:
df1.shape

(1398041, 52)

In [16]:
df1.isna().sum()

CIFNO                                 0
ACCOUNT_STATUS                    10268
PRODUCT_DESC                          0
SUB_PRODUCT_DESC                      0
BAL_OS                                0
NET_INTEREST_INCOME                   0
REGION_CD                             0
ACCOUNT_JOINT                   1311749
DPD_LAST_6_MONTH                1380708
NPA_FLAG                        1355721
NO_ACCOUNTS_SAVINGS              171654
SIX_MONTH_BAL_OS_SAVINGS         171479
NO_ACCOUNTS_CURRENT             1289465
SIX_MONTH_BAL_OS_CURRENT        1267195
NO_ACCOUNTS_FD                  1135689
SIX_MONTH_BAL_OS_FD             1122845
NO_ACCOUNTS_HOUSING             1380449
SIX_MONTH_BAL_OS_HOUSING        1379861
NO_ACCOUNTS_TERM                1354393
SIX_MONTH_BAL_OS_TERM           1349173
NO_ACCOUNTS_LEASING             1362212
SIX_MONTH_BAL_OS_LEASING        1359027
NO_ACCOUNTS_PAWNING             1276436
SIX_MONTH_BAL_OS_PAWNING        1276436
NO_ACCOUNTS_PERSONAL            1352643
SIX_MONTH_BAL_OS_PERSONAL       1350138
NO_ACCOUNTS_SHORT_TERM          1392177
SIX_MONTH_BAL_OS_SHORT_TERM     1391305
NO_ACCOUNTS_STAFF               1378311
SIX_MONTH_BAL_OS_STAFF          1377856
NO_ACCOUNTS_TRADE               1395768
SIX_MONTH_BAL_OS_TRADE          1394947
NO_ACCOUNTS_DEVELOPMENT         1366149
SIX_MONTH_BAL_OS_DEVELOPMENT    1363526
NO_ACCOUNTS_REFINANCE           1392405
SIX_MONTH_BAL_OS_REFINANCE      1391709
NO_ACCOUNTS_CARD                1187822
SIX_MONTH_BAL_OS_CARD           1183200
NO_ACCOUNTS_OD                  1364886
SIX_MONTH_BAL_OS_OD             1353216
TOTAL_AVG_BAL                        46
FD_AMOUNT_UNDER_LIEN            1396450
CURRENT_AMOUNT_UNDER_LIEN       1391295
SAVINGS_AMOUNT_UNDER_LIEN       1320561
CUSTOMER_PROFITABILITY               46
E_BANKING_ACCOUNTS              1136533
SOLO_ACCOUNTS                   1207668
DEBIT_CARD_USAGE                1071058
CREDIT_CARD_USAGE               1182287
PAYFAST_ACCOUNT                 1389269
NII                                  46
LNAMOUNT                        1339348
dtype: int64

In [17]:
df1.head(5)

,CIFNO,ACCOUNT_STATUS,PRODUCT_DESC,SUB_PRODUCT_DESC,BAL_OS,NET_INTEREST_INCOME,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII,LNAMOUNT
0,998101782755,D,Savings,SAVINGS - GENERAL,0.00,0.00,3,NaN,NaN,NaN,1.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0.00,NaN
1,998101242090,NaN,Savings,SAVINGS MAJOR INVESTMENT,5132.92,14.67,10,NaN,NaN,Y,3.0,19533.42,1.0,194303.61,NaN,NaN,2.0,7422954.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2174881.48,NaN,NaN,1.0,158714.15,NaN,NaN,9970386.80,NaN,NaN,107407.08,40740.15,1.0,Y,NaN,0.0,NaN,38478.15,NaN
6,998100738214,A,Savings,SAVINGS - GENERAL,21073.54,241.00,2,NaN,NaN,NaN,1.0,13147.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13147.64,NaN,NaN,NaN,241.00,NaN,NaN,NaN,NaN,NaN,241.00,NaN
7,998R00673750,A,Savings,SAVINGS - OTHERS,21.00,3.91,5,NaN,NaN,NaN,1.0,58.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.39,NaN,NaN,NaN,23.91,NaN,NaN,3400.0,NaN,NaN,3.91,NaN
8,998101075169,D,Savings,SAVINGS - OTHERS,0.00,0.00,6,NaN,NaN,NaN,2.0,38639.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38639.00,NaN,NaN,NaN,67.80,NaN,NaN,46500.0,NaN,NaN,17.80,NaN

In [18]:
# create ACCOUNT_STATUS column with "A" & "D"

In [19]:
df1['ACCOUNT_STATUS'] = df1['ACCOUNT_STATUS'].replace(['NORM', 'R', 'N', 'NEW'], 'A')

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\3870701875.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ACCOUNT_STATUS'] = df1['ACCOUNT_STATUS'].replace(['NORM', 'R', 'N', 'NEW'], 'A')

In [20]:
mode_value_AS = df1['ACCOUNT_STATUS'].mode()[0]
df1['ACCOUNT_STATUS'] = df1['ACCOUNT_STATUS'].fillna(mode_value_AS)

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\22010685.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ACCOUNT_STATUS'] = df1['ACCOUNT_STATUS'].fillna(mode_value_AS)

In [21]:
df1['ACCOUNT_STATUS'] = df1['ACCOUNT_STATUS'].replace(['D', 'U', 'BLCK', 'H', 'DCC', 'WROF', 'CLSB', 'NDCC', 'BULT',
       'EXPC', 'L', 'O', 'LOST', 'CLSC', 'EXST', 'S', 'NREN',
       'PICK', 'LEGL', 'VIRT', 'I', 'NONE', 'NCCC', 'CRPC', 'LOSS',
       'REIS'], 'D')

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\1345089179.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ACCOUNT_STATUS'] = df1['ACCOUNT_STATUS'].replace(['D', 'U', 'BLCK', 'H', 'DCC', 'WROF', 'CLSB', 'NDCC', 'BULT',

In [22]:
def active_status(x):
    if (x=="D"):
        return 0
    elif(x=="A"):
        return 1
    else:
        return 2
df1['ACCOUNT_STATUS'] = df1['ACCOUNT_STATUS'].apply(active_status)

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\2838623824.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ACCOUNT_STATUS'] = df1['ACCOUNT_STATUS'].apply(active_status)

In [23]:
df1['ACCOUNT_STATUS'].value_counts()

1    956106
0    441935
Name: ACCOUNT_STATUS, dtype: int64

In [24]:
def ACCOUNT_JOINT(x):
    if pd.isna(x):
        return 0
    elif x == "J":
        return 1
    else:
        return 2
df1['ACCOUNT_JOINT'] = df1['ACCOUNT_JOINT'].apply(ACCOUNT_JOINT)

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\3902859877.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ACCOUNT_JOINT'] = df1['ACCOUNT_JOINT'].apply(ACCOUNT_JOINT)

In [25]:
df1['ACCOUNT_JOINT'].value_counts()

0    1311749
1      86292
Name: ACCOUNT_JOINT, dtype: int64

In [26]:
def NPA_FLAG(x):
    if pd.isna(x):
        return 0
    elif x == "Y":
        return 1
    else:
        return 2
df1['NPA_FLAG'] = df1['NPA_FLAG'].apply(NPA_FLAG)

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\376666383.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['NPA_FLAG'] = df1['NPA_FLAG'].apply(NPA_FLAG)

In [27]:
df1['NPA_FLAG'].value_counts()

0    1355721
1      42320
Name: NPA_FLAG, dtype: int64

In [28]:
def SOLO_ACCOUNTS (x):
    if pd.isna(x):
        return 0
    elif x == "Y":
        return 1
    else:
        return 2
df1['SOLO_ACCOUNTS'] = df1['SOLO_ACCOUNTS'].apply(SOLO_ACCOUNTS)

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\1632691478.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['SOLO_ACCOUNTS'] = df1['SOLO_ACCOUNTS'].apply(SOLO_ACCOUNTS)

In [29]:
df1['SOLO_ACCOUNTS'].value_counts()

0    1207668
1     190373
Name: SOLO_ACCOUNTS, dtype: int64

In [30]:
def PAYFAST_ACCOUNT (x):
    if pd.isna(x):
        return 0
    elif x == "Y":
        return 1
    else:
        return 2
df1['PAYFAST_ACCOUNT'] = df1['PAYFAST_ACCOUNT'].apply(SOLO_ACCOUNTS)

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\551716998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['PAYFAST_ACCOUNT'] = df1['PAYFAST_ACCOUNT'].apply(SOLO_ACCOUNTS)

In [31]:
df1['PAYFAST_ACCOUNT'].value_counts()

0    1389269
1       8772
Name: PAYFAST_ACCOUNT, dtype: int64

In [32]:
df1["E_BANKING_ACCOUNTS"] = (df1['E_BANKING_ACCOUNTS'] > 0).astype(int)

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\804344623.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["E_BANKING_ACCOUNTS"] = (df1['E_BANKING_ACCOUNTS'] > 0).astype(int)

In [33]:
df1['E_BANKING_ACCOUNTS'].value_counts()

0    1136533
1     261508
Name: E_BANKING_ACCOUNTS, dtype: int64

In [34]:
df1.head(5)

,CIFNO,ACCOUNT_STATUS,PRODUCT_DESC,SUB_PRODUCT_DESC,BAL_OS,NET_INTEREST_INCOME,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII,LNAMOUNT
0,998101782755,0,Savings,SAVINGS - GENERAL,0.00,0.00,3,0,NaN,0,1.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,0,0,NaN,NaN,0,0.00,NaN
1,998101242090,1,Savings,SAVINGS MAJOR INVESTMENT,5132.92,14.67,10,0,NaN,1,3.0,19533.42,1.0,194303.61,NaN,NaN,2.0,7422954.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2174881.48,NaN,NaN,1.0,158714.15,NaN,NaN,9970386.80,NaN,NaN,107407.08,40740.15,1,1,NaN,0.0,0,38478.15,NaN
6,998100738214,1,Savings,SAVINGS - GENERAL,21073.54,241.00,2,0,NaN,0,1.0,13147.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13147.64,NaN,NaN,NaN,241.00,0,0,NaN,NaN,0,241.00,NaN
7,998R00673750,1,Savings,SAVINGS - OTHERS,21.00,3.91,5,0,NaN,0,1.0,58.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.39,NaN,NaN,NaN,23.91,0,0,3400.0,NaN,0,3.91,NaN
8,998101075169,0,Savings,SAVINGS - OTHERS,0.00,0.00,6,0,NaN,0,2.0,38639.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38639.00,NaN,NaN,NaN,67.80,0,0,46500.0,NaN,0,17.80,NaN

In [35]:
columns_to_replace=[
"BAL_OS",
"NET_INTEREST_INCOME",
"DPD_LAST_6_MONTH",
"NO_ACCOUNTS_SAVINGS",
"SIX_MONTH_BAL_OS_SAVINGS",
"NO_ACCOUNTS_CURRENT",
"SIX_MONTH_BAL_OS_CURRENT",
"NO_ACCOUNTS_FD",
"SIX_MONTH_BAL_OS_FD",
"NO_ACCOUNTS_HOUSING",
"SIX_MONTH_BAL_OS_HOUSING",
"NO_ACCOUNTS_TERM",
"SIX_MONTH_BAL_OS_TERM",
"NO_ACCOUNTS_LEASING",
"SIX_MONTH_BAL_OS_LEASING",
"NO_ACCOUNTS_PAWNING",
"SIX_MONTH_BAL_OS_PAWNING",
"NO_ACCOUNTS_PERSONAL",
"SIX_MONTH_BAL_OS_PERSONAL",
"NO_ACCOUNTS_SHORT_TERM",  
"SIX_MONTH_BAL_OS_SHORT_TERM",
"NO_ACCOUNTS_STAFF",
"SIX_MONTH_BAL_OS_STAFF",
"NO_ACCOUNTS_TRADE",
"SIX_MONTH_BAL_OS_TRADE",
"NO_ACCOUNTS_DEVELOPMENT",
"SIX_MONTH_BAL_OS_DEVELOPMENT",
"NO_ACCOUNTS_REFINANCE",
"SIX_MONTH_BAL_OS_REFINANCE",
"NO_ACCOUNTS_CARD",
"SIX_MONTH_BAL_OS_CARD",
"NO_ACCOUNTS_OD",
"SIX_MONTH_BAL_OS_OD",
"TOTAL_AVG_BAL",
"FD_AMOUNT_UNDER_LIEN",
"CURRENT_AMOUNT_UNDER_LIEN",
"SAVINGS_AMOUNT_UNDER_LIEN",
"CUSTOMER_PROFITABILITY",
"DEBIT_CARD_USAGE",
"CREDIT_CARD_USAGE",
"NII",
"LNAMOUNT"    
]

In [36]:
df1[columns_to_replace] = df1[columns_to_replace].fillna(0)

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\1304779616.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[columns_to_replace] = df1[columns_to_replace].fillna(0)

In [37]:
df1 = df1[(df1['ACCOUNT_STATUS'] == 1) & (df1['SUB_PRODUCT_DESC'] != 'STAFF LOANS') ]

In [38]:
df1['ACCOUNT_STATUS'].value_counts()

1    948535
Name: ACCOUNT_STATUS, dtype: int64

In [39]:
df1.isna().sum()

CIFNO                           0
ACCOUNT_STATUS                  0
PRODUCT_DESC                    0
SUB_PRODUCT_DESC                0
BAL_OS                          0
NET_INTEREST_INCOME             0
REGION_CD                       0
ACCOUNT_JOINT                   0
DPD_LAST_6_MONTH                0
NPA_FLAG                        0
NO_ACCOUNTS_SAVINGS             0
SIX_MONTH_BAL_OS_SAVINGS        0
NO_ACCOUNTS_CURRENT             0
SIX_MONTH_BAL_OS_CURRENT        0
NO_ACCOUNTS_FD                  0
SIX_MONTH_BAL_OS_FD             0
NO_ACCOUNTS_HOUSING             0
SIX_MONTH_BAL_OS_HOUSING        0
NO_ACCOUNTS_TERM                0
SIX_MONTH_BAL_OS_TERM           0
NO_ACCOUNTS_LEASING             0
SIX_MONTH_BAL_OS_LEASING        0
NO_ACCOUNTS_PAWNING             0
SIX_MONTH_BAL_OS_PAWNING        0
NO_ACCOUNTS_PERSONAL            0
SIX_MONTH_BAL_OS_PERSONAL       0
NO_ACCOUNTS_SHORT_TERM          0
SIX_MONTH_BAL_OS_SHORT_TERM     0
NO_ACCOUNTS_STAFF               0
SIX_MONTH_BAL_OS_STAFF          0
NO_ACCOUNTS_TRADE               0
SIX_MONTH_BAL_OS_TRADE          0
NO_ACCOUNTS_DEVELOPMENT         0
SIX_MONTH_BAL_OS_DEVELOPMENT    0
NO_ACCOUNTS_REFINANCE           0
SIX_MONTH_BAL_OS_REFINANCE      0
NO_ACCOUNTS_CARD                0
SIX_MONTH_BAL_OS_CARD           0
NO_ACCOUNTS_OD                  0
SIX_MONTH_BAL_OS_OD             0
TOTAL_AVG_BAL                   0
FD_AMOUNT_UNDER_LIEN            0
CURRENT_AMOUNT_UNDER_LIEN       0
SAVINGS_AMOUNT_UNDER_LIEN       0
CUSTOMER_PROFITABILITY          0
E_BANKING_ACCOUNTS              0
SOLO_ACCOUNTS                   0
DEBIT_CARD_USAGE                0
CREDIT_CARD_USAGE               0
PAYFAST_ACCOUNT                 0
NII                             0
LNAMOUNT                        0
dtype: int64

In [40]:
#filepath=r"C:/Users/15341/Desktop/HNBPROJ/Kau/final/finalpreprocess_corected.csv"
#df1.to_csv(filepath, index=False)

### Loan

In [41]:
loan_df = df1[(df1['PRODUCT_DESC'] == 'Loan') & (df1['LNAMOUNT'] >0) ]

In [42]:
loan_df.shape

(13618, 52)

In [43]:
loan_df.columns

Index(['CIFNO', 'ACCOUNT_STATUS', 'PRODUCT_DESC', 'SUB_PRODUCT_DESC', 'BAL_OS',
       'NET_INTEREST_INCOME', 'REGION_CD', 'ACCOUNT_JOINT', 'DPD_LAST_6_MONTH',
       'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS', 'SIX_MONTH_BAL_OS_SAVINGS',
       'NO_ACCOUNTS_CURRENT', 'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD',
       'SIX_MONTH_BAL_OS_FD', 'NO_ACCOUNTS_HOUSING',
       'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM', 'SIX_MONTH_BAL_OS_TERM',
       'NO_ACCOUNTS_LEASING', 'SIX_MONTH_BAL_OS_LEASING',
       'NO_ACCOUNTS_PAWNING', 'SIX_MONTH_BAL_OS_PAWNING',
       'NO_ACCOUNTS_PERSONAL', 'SIX_MONTH_BAL_OS_PERSONAL',
       'NO_ACCOUNTS_SHORT_TERM', 'SIX_MONTH_BAL_OS_SHORT_TERM',
       'NO_ACCOUNTS_STAFF', 'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE',
       'SIX_MONTH_BAL_OS_TRADE', 'NO_ACCOUNTS_DEVELOPMENT',
       'SIX_MONTH_BAL_OS_DEVELOPMENT', 'NO_ACCOUNTS_REFINANCE',
       'SIX_MONTH_BAL_OS_REFINANCE', 'NO_ACCOUNTS_CARD',
       'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD', 'SIX_MONTH_BAL_OS_OD',
       'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN', 'CURRENT_AMOUNT_UNDER_LIEN',
       'SAVINGS_AMOUNT_UNDER_LIEN', 'CUSTOMER_PROFITABILITY',
       'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS', 'DEBIT_CARD_USAGE',
       'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII', 'LNAMOUNT'],
      dtype='object')

In [44]:
loan_df1=loan_df[['CIFNO',  'PRODUCT_DESC', 'SUB_PRODUCT_DESC', 'BAL_OS',
       'NET_INTEREST_INCOME', 'REGION_CD', 'ACCOUNT_JOINT',
       'DPD_LAST_6_MONTH']]

In [45]:
from scipy.stats import mode

In [46]:
lo_df = loan_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'SUB_PRODUCT_DESC':lambda x: mode(x)[0][0],
                        'BAL_OS':'sum','NET_INTEREST_INCOME':'sum',"REGION_CD":lambda x: mode(x)[0][0],'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})
lo_df2=lo_df.sort_values(by=['SUB_PRODUCT_DESC','BAL_OS','NET_INTEREST_INCOME',"REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"],ascending=False)
lo_df3=lo_df2.groupby('CIFNO').first().reset_index()
lo_df3.head()

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\1259203839.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  lo_df = loan_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'SUB_PRODUCT_DESC':lambda x: mode(x)[0][0],
C:\Users\15694\AppData\Local\Temp\ipykernel_12844\1259203839.py:1: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html.
  lo_df = loan_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'SUB_PRODUCT_DESC':lambda x: mode(x)[0][0],
C:\Users\15694\AppData\Local\Temp\ipykernel_12844\1259203839.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  'BAL_OS':'sum','NET_INTEREST_INCOME':'sum',"REGION_CD":lambda x: mode(x)[0][0],'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})

,CIFNO,PRODUCT_DESC,SUB_PRODUCT_DESC,BAL_OS,NET_INTEREST_INCOME,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH
0,998000000102,Loan,PERSONAL LOANS,129609.51,362.32,3,0,0.0
1,998000000173,Loan,PERSONAL LOANS,1637529.58,1255.19,10,0,0.0
2,998000000262,Loan,TERM LOANS,157280.00,1766.76,8,0,0.0
3,998000001044,Loan,TERM LOANS,1105600.00,-3369.31,2,1,0.0
4,998000001498,Loan,PERSONAL LOANS,3478692.89,10697.47,3,0,0.0

In [47]:
unique_cifno_count_lo = lo_df3['CIFNO'].nunique()

if unique_cifno_count_lo == len(lo_df3):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [48]:
lo_df3.shape

(11836, 8)

In [49]:
loan_df2=loan_df[[
    "CIFNO",'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS',
       'SIX_MONTH_BAL_OS_SAVINGS', 'NO_ACCOUNTS_CURRENT',
       'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD', 'SIX_MONTH_BAL_OS_FD',
       'NO_ACCOUNTS_HOUSING', 'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM',
       'SIX_MONTH_BAL_OS_TERM', 'NO_ACCOUNTS_LEASING',
       'SIX_MONTH_BAL_OS_LEASING', 'NO_ACCOUNTS_PAWNING',
       'SIX_MONTH_BAL_OS_PAWNING', 'NO_ACCOUNTS_PERSONAL',
       'SIX_MONTH_BAL_OS_PERSONAL', 'NO_ACCOUNTS_SHORT_TERM',
       'SIX_MONTH_BAL_OS_SHORT_TERM', 'NO_ACCOUNTS_STAFF',
       'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE', 'SIX_MONTH_BAL_OS_TRADE',
       'NO_ACCOUNTS_DEVELOPMENT', 'SIX_MONTH_BAL_OS_DEVELOPMENT',
       'NO_ACCOUNTS_REFINANCE', 'SIX_MONTH_BAL_OS_REFINANCE',
       'NO_ACCOUNTS_CARD', 'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD',
       'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN',
       'CURRENT_AMOUNT_UNDER_LIEN', 'SAVINGS_AMOUNT_UNDER_LIEN',
       'CUSTOMER_PROFITABILITY', 'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS',
       'DEBIT_CARD_USAGE', 'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII',
       'LNAMOUNT']]

In [50]:
dlo=loan_df2.groupby('CIFNO').first().reset_index()

In [51]:
dlo.shape

(11836, 44)

In [52]:
final_loan_df=pd.merge(lo_df3, dlo, on='CIFNO', how='left')

In [53]:
final_loan_df.rename(columns={'DPD_LAST_6_MONTH': 'DPD_LAST_6_MONTH_LOAN'}, inplace=True)

In [54]:
final_loan_df['LNAMOUNT'].value_counts()

5.000000e+05    810
3.000000e+05    567
1.000000e+06    559
2.000000e+06    441
1.500000e+06    367
3.000000e+06    304
5.000000e+06    298
2.000000e+05    291
2.500000e+06    244
6.000000e+05    236
4.000000e+05    211
1.200000e+06    172
7.000000e+05    170
4.000000e+06    167
8.000000e+05    163
6.000000e+06    147
1.000000e+07    136
9.000000e+05    129
3.500000e+06    125
1.800000e+06    116
2.500000e+05    116
1.500000e+05    115
1.000000e+05    111
7.000000e+06     86
4.500000e+06     84
1.300000e+06     82
3.500000e+05     81
1.100000e+06     76
4.500000e+05     75
7.500000e+05     74
7.500000e+06     71
8.000000e+06     71
2.800000e+05     65
1.600000e+06     64
1.250000e+05     64
1.400000e+06     63
1.700000e+06     59
1.500000e+07     58
2.200000e+06     54
2.000000e+07     50
2.300000e+06     50
2.400000e+06     47
8.500000e+05     43
9.000000e+06     43
2.700000e+06     42
3.750000e+05     41
2.100000e+06     41
5.500000e+05     39
1.800000e+05     39
3.200000e+06     38
5.500000e+06     38
6.500000e+05     38
9.000000e+04     38
2.800000e+06     36
6.500000e+06     36
1.900000e+06     35
1.200000e+07     34
2.600000e+06     33
9.500000e+05     32
3.000000e+07     31
1.250000e+06     29
2.500000e+07     28
2.900000e+06     27
1.400000e+07     26
1.350000e+06     26
3.800000e+06     23
1.100000e+07     23
3.600000e+06     22
1.300000e+07     21
3.700000e+06     21
4.700000e+06     20
2.700000e+05     20
1.750000e+06     19
2.250000e+06     19
5.000000e+04     18
4.900000e+06     17
1.600000e+07     17
1.250000e+07     16
3.400000e+06     16
4.800000e+06     16
8.500000e+06     16
4.300000e+06     16
3.600000e+05     16
1.800000e+07     15
3.300000e+06     15
1.850000e+06     14
2.650000e+06     14
5.800000e+06     14
1.150000e+07     13
5.300000e+06     13
1.050000e+07     13
4.200000e+06     13
1.750000e+07     12
2.250000e+05     12
9.500000e+06     12
4.000000e+07     12
1.450000e+06     12
1.150000e+06     12
6.300000e+06     12
1.000000e+08     12
1.350000e+07     12
3.100000e+06     12
1.080000e+06     11
2.150000e+06     11
5.400000e+05     11
1.050000e+06     11
7.500000e+04     11
6.300000e+05     11
1.350000e+05     11
1.700000e+07     10
1.950000e+06     10
5.400000e+06     10
4.600000e+06     10
5.000000e+07     10
6.600000e+06     10
7.800000e+05     10
6.700000e+06      9
2.350000e+06      9
2.450000e+06      9
2.300000e+07      9
3.900000e+06      9
5.100000e+06      9
6.800000e+06      9
2.050000e+06      9
5.600000e+06      9
1.200000e+05      9
2.400000e+07      9
6.200000e+06      9
3.200000e+05      9
1.850000e+07      8
1.260000e+06      8
2.200000e+07      8
3.500000e+07      8
9.900000e+05      8
1.900000e+07      8
2.900000e+07      8
1.650000e+06      8
4.500000e+07      7
4.100000e+06      7
1.275000e+06      7
3.850000e+06      7
1.550000e+06      7
1.680000e+06      7
1.550000e+07      7
3.250000e+05      7
6.400000e+06      7
1.170000e+06      7
1.450000e+07      7
1.400000e+05      7
2.100000e+07      6
5.700000e+06      6
7.700000e+06      6
8.800000e+06      6
3.150000e+06      6
6.000000e+07      6
8.100000e+06      6
1.280000e+06      6
7.000000e+07      6
5.200000e+06      6
7.200000e+06      6
1.180000e+06      6
3.200000e+07      6
9.800000e+06      6
1.300000e+05      6
2.200000e+05      6
8.400000e+05      6
2.800000e+07      5
7.400000e+06      5
5.818500e+05      5
2.950000e+06      5
7.100000e+06      5
1.100000e+05      5
2.550000e+06      5
5.800000e+05      5
6.800000e+05      5
3.250000e+06      5
2.850000e+06      5
1.600000e+05      5
4.500000e+04      5
1.750000e+05      5
7.900000e+06      5
5.700000e+05      5
7.200000e+05      5
6.150000e+05      5
3.700000e+05      5
2.350000e+07      5
1.315000e+06      4
7.600000e+06      4
2.750000e+06      4
6.900000e+06      4
1.530000e+06      4
2.750000e+05      4
8.600000e+06      4
8.400000e+06      4
5.900000e+06      4
1.560000e+06      4
4.750000e+05      4
2.600000e+05      4
1.080000e+07      4
7.000000e+04      4
1.230000e+06      4
1.480000e+06      4
7.250000e+05      4
1.630000e+06      4
3.750000e+06      4
4.800000e+05      4
1.220000e+07      4
8.700000e+06      4
1.320000e+07      4
1.120000e+07      4
1.330000e+07      4
1.460000e+05      4
1.960000e+06      4
4.100000e+07      4
3.400000e+07      4
3.050000e+06      4
1.430000e+06      4
8.000000e+04      4
5.900000e+05      4
2.700000e+07      4
8.200000e+06      4
3.150000e+05      4
3.550000e+06      4
1.875000e+06      4
2.430000e+06      4
2.370000e+06      4
7.300000e+05      4
6.250000e+05      4
2.070000e+06      4
5.200000e+07      4
8.800000e+05      4
2.400000e+05      4
1.620000e+06      4
1.900000e+05      4
9.750000e+05      4
2.060000e+06      3
2.125000e+06      3
9.930000e+05      3
6.200000e+05      3
4.200000e+05      3
5.100000e+05      3
1.930000e+06      3
1.890000e+07      3
2.100000e+05      3
9.200000e+05      3
4.600000e+07      3
7.951500e+05      3
5.250000e+06      3
2.250000e+07      3
5.650000e+05      3
9.150000e+05      3
3.100000e+07      3
2.375000e+06      3
4.900000e+05      3
2.320000e+06      3
9.450000e+05      3
6.000000e+04      3
1.440000e+06      3
1.650000e+07      3
4.950000e+06      3
4.550000e+06      3
6.700000e+05      3
7.500000e+07      3
4.850000e+06      3
1.080000e+05      3
8.900000e+06      3
2.450000e+07      3
1.400000e+08      3
5.600000e+07      3
7.100000e+05      3
2.140000e+06      3
1.925000e+06      3
1.270000e+07      3
1.920000e+07      3
1.090000e+07      3
1.470000e+07      3
1.660000e+06      3
3.120000e+06      3
2.925000e+06      3
1.125000e+06      3
2.330000e+07      3
2.300000e+05      3
3.350000e+06      3
7.950000e+05      3
2.390000e+06      3
6.250000e+06      3
1.330000e+06      3
9.558000e+05      3
5.950000e+06      3
1.270000e+06      3
1.065000e+06      3
2.240000e+06      3
8.250000e+05      3
1.490000e+06      3
2.690000e+06      3
9.650000e+05      3
4.650000e+06      3
6.950000e+05      3
8.000000e+07      3
9.100000e+06      3
1.150000e+05      3
1.025000e+06      3
1.160000e+07      3
4.250000e+06      3
1.125000e+05      3
4.350000e+06      3
5.750000e+05      3
1.845000e+06      3
3.100000e+05      3
9.600000e+06      3
3.630000e+06      3
1.460000e+06      3
5.500000e+07      3
1.290000e+06      3
6.100000e+06      3
1.430000e+07      3
2.110000e+07      3
1.460000e+07      3
2.900000e+05      2
1.165000e+06      2
9.100000e+05      2
3.360000e+06      2
2.130000e+05      2
9.300000e+05      2
2.380000e+06      2
1.580000e+06      2
2.160000e+05      2
1.275000e+07      2
1.770000e+06      2
4.250000e+07      2
1.380000e+07      2
8.550000e+05      2
1.620000e+07      2
2.330000e+06      2
3.340000e+06      2
1.260000e+05      2
1.155000e+06      2
2.495000e+06      2
1.840000e+06      2
3.040000e+06      2
4.200000e+07      2
7.400000e+05      2
2.050000e+07      2
1.725000e+06      2
6.150000e+06      2
1.110000e+07      2
4.350000e+07      2
9.700000e+06      2
1.390000e+07      2
2.680000e+06      2
3.750000e+07      2
7.600000e+05      2
2.460000e+06      2
1.111000e+06      2
9.800000e+05      2
1.720000e+06      2
2.730000e+06      2
1.950000e+07      2
8.100000e+05      2
5.370000e+06      2
2.380000e+05      2
1.575000e+06      2
1.785000e+06      2
2.470000e+06      2
6.500000e+04      2
2.275000e+06      2
1.870000e+06      2
2.190000e+06      2
1.060000e+06      2
8.350000e+06      2
4.050000e+05      2
1.560000e+07      2
1.095000e+07      2
7.650000e+05      2
4.600000e+05      2
8.250000e+06      2
1.500000e+08      2
1.060000e+07      2
2.195000e+06      2
3.525000e+06      2
2.520000e+06      2
1.310000e+07      2
5.850000e+05      2
2.780000e+05      2
8.600000e+04      2
9.000000e+07      2
9.720000e+05      2
3.730000e+06      2
2.700000e+04      2
1.995000e+06      2
4.800000e+07      2
1.470000e+06      2
3.900000e+07      2
1.990000e+06      2
2.480000e+06      2
2.965000e+06      2
5.250000e+05      2
8.300000e+06      2
7.700000e+05      2
1.390000e+06      2
1.230000e+07      2
3.800000e+05      2
3.300000e+05      2
1.690000e+06      2
4.400000e+06      2
3.075000e+06      2
1.145000e+06      2
1.755000e+06      2
2.025000e+05      2
2.340000e+06      2
4.750000e+06      2
2.090000e+06      2
2.115000e+06      2
1.180000e+07      2
6.750000e+06      2
3.600000e+07      2
1.360000e+06      2
4.520000e+06      2
5.850000e+07      2
5.750000e+06      2
2.000000e+09      2
1.290000e+05      2
4.300000e+05      2
1.015000e+07      2
4.820000e+06      2
1.265000e+06      2
2.750000e+07      2
7.000000e+08      2
2.030000e+06      2
2.145000e+06      2
7.800000e+06      2
8.430000e+05      2
6.400000e+05      2
2.970000e+05      2
2.830000e+06      2
1.237500e+07      2
8.600000e+05      2
1.420000e+06      2
1.170000e+05      2
1.025000e+07      2
1.070000e+06      2
6.550000e+06      2
7.250000e+06      2
8.890000e+05      2
8.700000e+05      2
3.010000e+07      2
1.425000e+06      2
1.300000e+08      2
6.650000e+06      2
1.663000e+06      2
2.310000e+06      2
1.510000e+06      2
5.650000e+06      2
2.264000e+06      2
2.050000e+05      2
2.695000e+06      2
2.010000e+06      2
1.980000e+06      2
2.150000e+07      2
2.194000e+06      2
1.830000e+06      2
1.475000e+06      2
5.850000e+06      2
2.539800e+06      2
2.790000e+06      2
4.175000e+06      2
2.600000e+07      2
1.020000e+06      2
1.775000e+06      2
9.500000e+07      2
2.295000e+06      2
3.400000e+05      2
4.830000e+05      2
1.140000e+07      2
5.550000e+06      2
2.825000e+06      2
8.300000e+05      2
2.280000e+06      2
2.570000e+06      2
1.130000e+06      2
1.170000e+07      2
1.740000e+06      2
7.300000e+06      2
4.620000e+06      1
4.487580e+06      1
3.660000e+08      1
4.760091e+06      1
9.622264e+05      1
9.008087e+04      1
2.595395e+05      1
2.692168e+06      1
6.025000e+06      1
3.711262e+06      1
7.162092e+06      1
4.960000e+06      1
1.110000e+06      1
1.297000e+06      1
3.411000e+05      1
2.193000e+06      1
1.831098e+06      1
7.150000e+07      1
1.079670e+07      1
2.792000e+06      1
1.240000e+08      1
2.535000e+06      1
7.811960e+03      1
6.282122e+06      1
2.922112e+05      1
9.966592e+07      1
7.710579e+05      1
4.480000e+06      1
1.471291e+08      1
3.480500e+07      1
3.468000e+06      1
3.553116e+04      1
4.160000e+05      1
5.265000e+07      1
3.076000e+06      1
1.925000e+05      1
1.301130e+06      1
6.240000e+05      1
2.958678e+06      1
1.711237e+05      1
1.830315e+06      1
1.100377e+07      1
1.379596e+06      1
1.343327e+07      1
2.747697e+06      1
1.895322e+07      1
5.822222e+06      1
1.444073e+06      1
1.057410e+07      1
1.194376e+07      1
2.885907e+06      1
2.689420e+06      1
3.967832e+06      1
6.149551e+05      1
1.900000e+08      1
2.650000e+07      1
1.948911e+06      1
1.334370e+08      1
8.450490e+06      1
5.331140e+07      1
3.173199e+06      1
1.813259e+08      1
2.601967e+07      1
1.479160e+07      1
1.820000e+08      1
2.112090e+06      1
5.246394e+05      1
4.527964e+05      1
1.627484e+06      1
3.219370e+06      1
4.736060e+06      1
1.083000e+06      1
5.372574e+05      1
3.836743e+06      1
4.470681e+07      1
1.373000e+06      1
6.927685e+04      1
2.083436e+06      1
1.875000e+07      1
2.503000e+08      1
4.650000e+08      1
1.230613e+06      1
2.801000e+08      1
4.551188e+04      1
1.115000e+06      1
1.214554e+07      1
4.120000e+06      1
2.802298e+06      1
1.357000e+08      1
1.480000e+07      1
3.850000e+07      1
7.322137e+06      1
1.679871e+04      1
8.742494e+06      1
2.756613e+05      1
2.583823e+05      1
4.000000e+09      1
3.638712e+06      1
1.110629e+07      1
6.520000e+07      1
1.300685e+04      1
7.722360e+05      1
3.799493e+06      1
1.950000e+05      1
1.223293e+07      1
1.040137e+04      1
6.090000e+06      1
5.169852e+06      1
4.390000e+07      1
4.442589e+07      1
7.953908e+06      1
8.320000e+05      1
1.640000e+06      1
5.294384e+05      1
3.123962e+06      1
1.725000e+07      1
7.100000e+07      1
1.217289e+07      1
5.463725e+08      1
4.763184e+06      1
4.000000e+04      1
3.941223e+05      1
4.006337e+06      1
2.097298e+06      1
3.900000e+05      1
7.320000e+05      1
9.174759e+05      1
3.320000e+07      1
1.107000e+08      1
1.903824e+06      1
4.940400e+06      1
1.150000e+08      1
1.492316e+07      1
9.027560e+06      1
1.307000e+08      1
6.110000e+05      1
2.767800e+07      1
2.755000e+06      1
8.610000e+07      1
2.329299e+06      1
6.147768e+05      1
1.862500e+06      1
8.024112e+07      1
4.650000e+07      1
4.540000e+07      1
5.200924e+07      1
2.178000e+07      1
4.833420e+06      1
1.095000e+08      1
2.583045e+06      1
2.756769e+06      1
8.526565e+06      1
4.455000e+07      1
6.940000e+05      1
3.441230e+05      1
2.672690e+06      1
4.909973e+06      1
1.897609e+06      1
1.618004e+06      1
1.890000e+05      1
8.224544e+06      1
1.023495e+07      1
7.547160e+06      1
2.493332e+07      1
5.784000e+06      1
2.860000e+05      1
4.238517e+06      1
1.059819e+08      1
8.631806e+05      1
3.036500e+07      1
1.047740e+07      1
2.687604e+06      1
1.392500e+07      1
3.722042e+07      1
3.363163e+06      1
4.910525e+07      1
5.342993e+07      1
3.733989e+06      1
3.610000e+05      1
4.530000e+07      1
2.229845e+07      1
3.417770e+06      1
4.224869e+06      1
4.330000e+06      1
8.382571e+06      1
1.151172e+06      1
1.000324e+06      1
8.970000e+06      1
5.580000e+06      1
6.371129e+06      1
3.096202e+06      1
2.630908e+05      1
8.390226e+06      1
1.370648e+07      1
4.760000e+06      1
5.968191e+06      1
4.150000e+07      1
1.487696e+06      1
5.582957e+06      1
1.301889e+07      1
1.709418e+06      1
1.478453e+07      1
1.103332e+06      1
2.303560e+03      1
7.897764e+04      1
1.825000e+06      1
1.686957e+05      1
4.184529e+06      1
2.729497e+05      1
6.038526e+04      1
2.181273e+05      1
4.609717e+06      1
8.846292e+06      1
6.576000e+07      1
1.080000e+08      1
5.806076e+08      1
4.514820e+07      1
1.656000e+06      1
4.887000e+06      1
9.129313e+06      1
1.056012e+07      1
2.315000e+06      1
3.970000e+06      1
1.315000e+07      1
1.446200e+06      1
3.995000e+07      1
1.220000e+06      1
2.852294e+06      1
2.292000e+06      1
4.048394e+06      1
2.693968e+04      1
3.216414e+07      1
1.562500e+07      1
1.209858e+05      1
5.040000e+06      1
8.099025e+08      1
5.646200e+08      1
4.961480e+07      1
3.457992e+06      1
3.151460e+07      1
5.053500e+07      1
4.880000e+07      1
2.582958e+06      1
1.213345e+06      1
1.657610e+07      1
7.214742e+06      1
2.702795e+07      1
3.286048e+06      1
1.655000e+07      1
1.300830e+09      1
5.620132e+05      1
7.594591e+07      1
4.661152e+05      1
6.875000e+06      1
1.360000e+07      1
1.205000e+07      1
1.861834e+06      1
1.056000e+06      1
9.158732e+05      1
3.017512e+05      1
1.932000e+06      1
1.386400e+07      1
4.130000e+06      1
3.059806e+04      1
3.500000e+08      1
3.799633e+07      1
2.668729e+07      1
4.900133e+08      1
1.110000e+08      1
4.060000e+06      1
5.474036e+05      1
1.207617e+07      1
1.287260e+07      1
1.540000e+06      1
6.245000e+06      1
3.797741e+06      1
1.117924e+06      1
4.933000e+07      1
6.900000e+05      1
2.912473e+05      1
9.682249e+04      1
4.812500e+05      1
1.326225e+07      1
1.320360e+05      1
2.925000e+07      1
4.270000e+05      1
2.280000e+07      1
5.324942e+06      1
2.515081e+08      1
9.250000e+05      1
2.655000e+06      1
1.713102e+05      1
5.433706e+07      1
1.650000e+05      1
6.628070e+06      1
1.738979e+08      1
3.210000e+06      1
7.434294e+06      1
1.154531e+09      1
3.444000e+07      1
3.897917e+04      1
6.587612e+07      1
2.785000e+07      1
2.077280e+06      1
1.270200e+07      1
3.835590e+06      1
1.263215e+07      1
7.873720e+06      1
5.678287e+06      1
1.074200e+07      1
3.048891e+08      1
4.114139e+06      1
5.470000e+07      1
1.756071e+06      1
2.465000e+06      1
2.770000e+06      1
6.970000e+05      1
2.640000e+06      1
7.300000e+04      1
7.271071e+06      1
6.410000e+05      1
1.133294e+06      1
8.520178e+04      1
3.851780e+06      1
2.434630e+06      1
2.230000e+07      1
3.365000e+06      1
6.870774e+06      1
3.046705e+08      1
1.928050e+06      1
8.145065e+06      1
1.261657e+06      1
1.794600e+05      1
2.820000e+06      1
3.812737e+06      1
2.583000e+06      1
3.652423e+06      1
2.180800e+06      1
2.523803e+06      1
3.520000e+06      1
4.478450e+05      1
3.745000e+06      1
1.180000e+05      1
5.262122e+05      1
6.179501e+06      1
1.852000e+06      1
1.894208e+06      1
9.800000e+04      1
1.030484e+06      1
1.348993e+07      1
2.090000e+07      1
2.217300e+07      1
3.907498e+07      1
5.856500e+07      1
7.092160e+05      1
9.604039e+06      1
8.796289e+05      1
8.850000e+06      1
7.944272e+05      1
1.340000e+08      1
1.615000e+07      1
1.370000e+07      1
1.408000e+08      1
4.073500e+06      1
1.008000e+07      1
1.898000e+07      1
6.450000e+07      1
3.636000e+06      1
1.915000e+06      1
2.116000e+06      1
6.889851e+06      1
5.995000e+06      1
3.057247e+07      1
1.199000e+06      1
2.570000e+07      1
2.747000e+06      1
1.841400e+07      1
3.282981e+05      1
1.956000e+06      1
3.005000e+06      1
2.427000e+06      1
3.751435e+06      1
2.930000e+06      1
2.425000e+06      1
2.711693e+07      1
1.021000e+06      1
1.726000e+06      1
1.965000e+06      1
9.370000e+05      1
2.056000e+06      1
1.187310e+08      1
2.698000e+08      1
6.990000e+07      1
1.566030e+08      1
3.370000e+05      1
3.189000e+06      1
1.287000e+06      1
4.860000e+06      1
1.980000e+05      1
2.290000e+06      1
2.390000e+05      1
1.944000e+05      1
5.386500e+05      1
3.820000e+05      1
3.880000e+06      1
3.293000e+06      1
6.443816e+07      1
5.400000e+07      1
3.109000e+06      1
1.648000e+06      1
1.847000e+06      1
2.260000e+06      1
7.875000e+06      1
2.135000e+06      1
4.260205e+07      1
6.825000e+06      1
6.819000e+06      1
1.305271e+06      1
2.856100e+06      1
5.430257e+05      1
3.030000e+06      1
7.550000e+05      1
2.660000e+06      1
2.589139e+06      1
3.838808e+05      1
3.310670e+03      1
4.125000e+05      1
2.058425e+04      1
2.870000e+06      1
1.880000e+07      1
1.346000e+06      1
7.170000e+05      1
1.028000e+06      1
2.742000e+06      1
5.680000e+06      1
2.105000e+06      1
4.702421e+06      1
3.430000e+06      1
1.445000e+06      1
9.458702e+05      1
2.513125e+05      1
2.488000e+06      1
4.975876e+06      1
2.911000e+06      1
6.912000e+06      1
4.090541e+06      1
5.517482e+05      1
4.870799e+05      1
2.630000e+06      1
2.895000e+07      1
3.850000e+08      1
1.514000e+06      1
5.669158e+05      1
5.742505e+05      1
4.675858e+06      1
2.765000e+06      1
1.250000e+08      1
3.238000e+06      1
1.866800e+05      1
3.780000e+05      1
4.751007e+07      1
5.970000e+06      1
4.807000e+06      1
1.281000e+06      1
2.164000e+06      1
7.110000e+05      1
1.985000e+06      1
7.900000e+05      1
7.209323e+06      1
2.133911e+06      1
8.600000e+07      1
4.700000e+07      1
1.323000e+05      1
5.777000e+06      1
3.271000e+06      1
1.320000e+06      1
2.623000e+06      1
2.785000e+06      1
8.762994e+05      1
2.788000e+06      1
2.384000e+06      1
9.600000e+05      1
1.987524e+08      1
1.050000e+05      1
1.372500e+07      1
1.867000e+06      1
6.910000e+05      1
6.565000e+06      1
1.260000e+07      1
1.162500e+07      1
2.220000e+07      1
5.325000e+06      1
2.960000e+05      1
4.556115e+07      1
2.110000e+06      1
6.656700e+05      1
8.230000e+05      1
8.980000e+05      1
1.860000e+07      1
6.525000e+05      1
7.125000e+06      1
1.760000e+06      1
6.592000e+06      1
1.175000e+06      1
1.340000e+05      1
2.115000e+05      1
2.360000e+05      1
2.181500e+05      1
2.695000e+07      1
6.850000e+06      1
5.522000e+07      1
1.350000e+08      1
1.549800e+07      1
3.650000e+07      1
3.528000e+06      1
1.660000e+05      1
1.187400e+08      1

In [55]:
final_loan_df= final_loan_df.drop(columns=['NET_INTEREST_INCOME',"SUB_PRODUCT_DESC",'LNAMOUNT'])

In [56]:
final_loan_df.shape

(11836, 48)

In [57]:
final_loan_df.head(10)

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH_LOAN,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,998000000102,Loan,129609.51,3,0,0.0,0,4.0,699504.75,0.0,0.00,3.0,378962.46,0.0,0.00,1.0,41495.97,0.0,0.0,0.0,0.0,2.0,2005943.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,20623.80,0.0,0.00,3146530.15,0.0,0.0,0.0,13770.79,1,1,200131.0,61300.72,0,12645.79
1,998000000173,Loan,1637529.58,10,0,0.0,0,3.0,53083.62,0.0,0.00,1.0,2838709.68,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,1.0,1751763.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,4643556.31,0.0,0.0,0.0,1560.99,1,0,0.0,0.00,0,1560.99
2,998000000262,Loan,157280.00,8,0,0.0,0,3.0,125762.58,0.0,0.00,4.0,2130590.11,0.0,0.00,1.0,180316.12,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,227326.09,1.0,126526.97,2790521.87,0.0,0.0,0.0,8324.88,0,0,96000.0,0.00,0,7884.88
3,998000001044,Loan,1105600.00,2,1,0.0,0,1.0,5089.71,0.0,0.00,2.0,7822222.22,0.0,0.00,2.0,1550494.29,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,9377806.22,0.0,0.0,0.0,48863.78,0,0,0.0,0.00,0,48863.78
4,998000001498,Loan,3478692.89,3,0,0.0,1,2.0,427008.66,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,1.0,3800049.63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,4227058.29,0.0,0.0,0.0,11543.94,1,0,0.0,0.00,0,11483.94
5,998000001736,Loan,599050.90,3,0,0.0,1,1.0,11793.21,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,1.0,636473.52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,49257.09,0.0,0.00,697523.82,0.0,0.0,0.0,5631.21,0,1,56500.0,0.00,0,2186.21
6,998000001754,Loan,1630737.88,4,0,0.0,0,2.0,15478.49,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,1.0,1824467.46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3370.81,0.0,0.00,1843316.76,0.0,0.0,0.0,7324.43,0,0,14500.0,0.00,0,6329.43
7,998000001999,Loan,251922.66,3,0,4.0,0,1.0,480.89,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,1.0,318474.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,318955.39,0.0,0.0,20.0,665.31,0,0,0.0,0.00,0,665.31
8,998000003371,Loan,2000.00,2,1,0.0,0,6.0,956716.52,1.0,11859.13,8.0,11408662.80,0.0,0.00,1.0,100314.19,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,197537.59,0.0,0.00,12675090.23,0.0,0.0,0.0,12513.37,1,0,53800.0,59965.21,0,12333.37
9,998000003392,Loan,8003312.00,3,0,0.0,0,4.0,3247868.56,1.0,52162.42,1.0,4000000.00,2.0,8296270.82,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,15596301.80,0.0,0.0,0.0,15662.21,1,0,2396000.0,0.00,0,15642.21

In [58]:
unique_cifno_count = final_loan_df['CIFNO'].nunique()

if unique_cifno_count == len(final_loan_df):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [59]:
#filepath=r"C:/Users/15341/Desktop/HNBPROJ/Kau/final/loan_corected_F.csv"
#final_loan_df.to_csv(filepath, index=False)

### Savings

In [60]:
savings_df = df1[(df1['PRODUCT_DESC'] == 'Savings') ]

In [61]:
savings_df['DPD_LAST_6_MONTH'].value_counts()

0.0    584230
Name: DPD_LAST_6_MONTH, dtype: int64

In [62]:
savings_df.shape

(584230, 52)

In [63]:
sav_df1=savings_df[['CIFNO',  'PRODUCT_DESC', 'BAL_OS',
        'REGION_CD', 'ACCOUNT_JOINT']]

In [64]:
sa_df = sav_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({
                        'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],'ACCOUNT_JOINT':lambda x: mode(x)[0][0]})
sa_df2=sa_df.sort_values(by=['BAL_OS',"REGION_CD",'ACCOUNT_JOINT'],ascending=False)
sa_df3=sa_df2.groupby('CIFNO').first().reset_index()
sa_df3.head()

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\994507151.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],'ACCOUNT_JOINT':lambda x: mode(x)[0][0]})

          CIFNO PRODUCT_DESC     BAL_OS  REGION_CD  ACCOUNT_JOINT
0  998000000102      Savings   22528.94          1              0
1  998000000104      Savings  387292.75          1              0
2  998000000108      Savings    3788.24          1              0
3  998000000120      Savings  381245.89          1              0
4  998000000121      Savings   49700.92          1              0

In [65]:
sa_df3.shape

(555282, 5)

In [66]:
unique_cifno_count_sa = sa_df3['CIFNO'].nunique()

if unique_cifno_count_sa == len(sa_df3):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [67]:
sa_df3.shape

(555282, 5)

In [68]:
sav_df2=savings_df[[
"CIFNO",'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS',
       'SIX_MONTH_BAL_OS_SAVINGS', 'NO_ACCOUNTS_CURRENT',
       'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD', 'SIX_MONTH_BAL_OS_FD',
       'NO_ACCOUNTS_HOUSING', 'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM',
       'SIX_MONTH_BAL_OS_TERM', 'NO_ACCOUNTS_LEASING',
       'SIX_MONTH_BAL_OS_LEASING', 'NO_ACCOUNTS_PAWNING',
       'SIX_MONTH_BAL_OS_PAWNING', 'NO_ACCOUNTS_PERSONAL',
       'SIX_MONTH_BAL_OS_PERSONAL', 'NO_ACCOUNTS_SHORT_TERM',
       'SIX_MONTH_BAL_OS_SHORT_TERM', 'NO_ACCOUNTS_STAFF',
       'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE', 'SIX_MONTH_BAL_OS_TRADE',
       'NO_ACCOUNTS_DEVELOPMENT', 'SIX_MONTH_BAL_OS_DEVELOPMENT',
       'NO_ACCOUNTS_REFINANCE', 'SIX_MONTH_BAL_OS_REFINANCE',
       'NO_ACCOUNTS_CARD', 'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD',
       'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN',
       'CURRENT_AMOUNT_UNDER_LIEN', 'SAVINGS_AMOUNT_UNDER_LIEN',
       'CUSTOMER_PROFITABILITY', 'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS',
       'DEBIT_CARD_USAGE', 'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII'
       ]]

In [69]:
dsav=sav_df2.groupby('CIFNO').first().reset_index()

In [70]:
dsav.shape

(555282, 43)

In [71]:
final_sav_df=pd.merge(sa_df3, dsav, on='CIFNO', how='left')

In [72]:
final_sav_df.shape

(555282, 47)

In [73]:
final_sav_df.head(10)

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,998000000102,Savings,22528.94,1,0,0,4.0,699504.75,0.0,0.00,3.0,378962.46,0.0,0.0,1.0,41495.97,0.0,0.0,0.0,0.0,2.0,2005943.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,20623.8,0.0,0.0,3146530.15,0.0,0.0,0.0,13770.79,1,1,200131.0,61300.72,0,12645.79
1,998000000104,Savings,387292.75,1,0,0,1.0,609042.79,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,536.0,0.0,0.0,609578.79,0.0,0.0,0.0,6714.23,0,0,0.0,300.00,0,4214.23
2,998000000108,Savings,3788.24,1,0,0,2.0,22063.95,0.0,0.00,1.0,182361.45,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,204425.40,0.0,0.0,0.0,389.71,0,0,0.0,0.00,0,389.71
3,998000000120,Savings,381245.89,1,0,0,4.0,563972.29,1.0,154321.43,5.0,48432671.21,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49150964.93,0.0,0.0,0.0,71516.67,1,0,0.0,0.00,0,71516.67
4,998000000121,Savings,49700.92,1,0,0,2.0,73222.63,0.0,0.00,1.0,500000.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,573222.63,0.0,0.0,0.0,2043.74,1,0,0.0,0.00,0,2043.74
5,998000000131,Savings,10872.00,1,0,0,3.0,206569.08,1.0,158171.26,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,364740.34,0.0,0.0,0.0,339.21,1,0,0.0,0.00,0,254.21
6,998000000171,Savings,37199.67,3,0,0,2.0,205520.82,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,205520.82,0.0,0.0,0.0,279.07,0,0,0.0,0.00,0,279.07
7,998000000173,Savings,217.24,10,0,0,3.0,53083.62,0.0,0.00,1.0,2838709.68,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,1751763.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4643556.31,0.0,0.0,0.0,1560.99,1,0,0.0,0.00,0,1560.99
8,998000000175,Savings,107.47,1,0,0,4.0,125131.39,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,125131.39,0.0,0.0,0.0,473.87,0,0,0.0,0.00,0,473.87
9,998000000186,Savings,0.00,2,0,0,1.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,20.0,0.00,0,0,0.0,0.00,0,0.00

In [74]:
unique_cifno_count = final_sav_df['CIFNO'].nunique()

if unique_cifno_count == len(final_sav_df):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

### Time Deposits

In [75]:
TimeDep_df = df1[(df1['PRODUCT_DESC'] == 'Time Deposits')]

In [76]:
TimeDep_df['DPD_LAST_6_MONTH'].value_counts()

0.0    123829
Name: DPD_LAST_6_MONTH, dtype: int64

In [77]:
TimeDep_df.shape

(123829, 52)

In [78]:
TimeDep_df1=TimeDep_df[['CIFNO',  'PRODUCT_DESC', 'BAL_OS','REGION_CD', 'ACCOUNT_JOINT']]

In [79]:
TD_df = TimeDep_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
                                                                                'ACCOUNT_JOINT':lambda x: mode(x)[0][0]})
TD_df2=TD_df.sort_values(by=['BAL_OS',"REGION_CD",'ACCOUNT_JOINT'],ascending=False)
TD_df3=TD_df2.groupby('CIFNO').first().reset_index()
TD_df3.head()

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\2934838866.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  TD_df = TimeDep_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
C:\Users\15694\AppData\Local\Temp\ipykernel_12844\2934838866.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  'ACCOUNT_JOINT':lambda x: mode(x)[0][0]})

          CIFNO   PRODUCT_DESC      BAL_OS  REGION_CD  ACCOUNT_JOINT
0  998000000105  Time Deposits   466894.16          1              0
1  998000000108  Time Deposits   190986.39          1              0
2  998000000120  Time Deposits  9000000.00          1              0
3  998000000121  Time Deposits   500000.00          3              0
4  998000000173  Time Deposits  4000000.00          1              0

In [80]:
TD_df3.shape

(90357, 5)

In [81]:
unique_cifno_count_TD = TD_df3['CIFNO'].nunique()

if unique_cifno_count_TD == len(TD_df3):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [82]:
TimeDep_df2=TimeDep_df[[
"CIFNO",'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS',
       'SIX_MONTH_BAL_OS_SAVINGS', 'NO_ACCOUNTS_CURRENT',
       'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD', 'SIX_MONTH_BAL_OS_FD',
       'NO_ACCOUNTS_HOUSING', 'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM',
       'SIX_MONTH_BAL_OS_TERM', 'NO_ACCOUNTS_LEASING',
       'SIX_MONTH_BAL_OS_LEASING', 'NO_ACCOUNTS_PAWNING',
       'SIX_MONTH_BAL_OS_PAWNING', 'NO_ACCOUNTS_PERSONAL',
       'SIX_MONTH_BAL_OS_PERSONAL', 'NO_ACCOUNTS_SHORT_TERM',
       'SIX_MONTH_BAL_OS_SHORT_TERM', 'NO_ACCOUNTS_STAFF',
       'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE', 'SIX_MONTH_BAL_OS_TRADE',
       'NO_ACCOUNTS_DEVELOPMENT', 'SIX_MONTH_BAL_OS_DEVELOPMENT',
       'NO_ACCOUNTS_REFINANCE', 'SIX_MONTH_BAL_OS_REFINANCE',
       'NO_ACCOUNTS_CARD', 'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD',
       'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN',
       'CURRENT_AMOUNT_UNDER_LIEN', 'SAVINGS_AMOUNT_UNDER_LIEN',
       'CUSTOMER_PROFITABILITY', 'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS',
       'DEBIT_CARD_USAGE', 'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII']]

In [83]:
dTD=TimeDep_df2.groupby('CIFNO').first().reset_index()

In [84]:
dTD.shape

(90357, 43)

In [85]:
final_TD_df=pd.merge(TD_df3, dTD, on='CIFNO', how='left')

In [86]:
final_TD_df.shape

(90357, 47)

In [87]:
final_TD_df.head(10)

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,998000000105,Time Deposits,466894.16,1,0,0,1.0,1038017.98,0.0,0.00,3.0,2327968.10,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,3365986.08,0.0,0.0,0.0,17930.85,0,0,0.0,0.00,0,17930.85
1,998000000108,Time Deposits,190986.39,1,0,0,2.0,22063.95,0.0,0.00,1.0,182361.45,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,204425.40,0.0,0.0,0.0,389.71,0,0,0.0,0.00,0,389.71
2,998000000120,Time Deposits,9000000.00,1,0,0,4.0,563972.29,1.0,154321.43,5.0,48432671.21,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,49150964.93,0.0,0.0,0.0,71516.67,1,0,0.0,0.00,0,71516.67
3,998000000121,Time Deposits,500000.00,3,0,0,2.0,73222.63,0.0,0.00,1.0,500000.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,573222.63,0.0,0.0,0.0,2043.74,1,0,0.0,0.00,0,2043.74
4,998000000173,Time Deposits,4000000.00,1,0,0,3.0,53083.62,0.0,0.00,1.0,2838709.68,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,1751763.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,4643556.31,0.0,0.0,0.0,1560.99,1,0,0.0,0.00,0,1560.99
5,998000000205,Time Deposits,12000000.00,10,0,0,2.0,8240231.40,0.0,0.00,4.0,12000000.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,20240231.40,0.0,0.0,0.0,91475.43,0,0,0.0,0.00,0,91455.43
6,998000000216,Time Deposits,2000000.00,3,1,0,2.0,274472.99,0.0,0.00,3.0,3500000.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,3774472.99,0.0,0.0,0.0,7539.82,0,0,30000.0,0.00,0,7449.82
7,998000000223,Time Deposits,592088.07,2,0,0,1.0,223685.37,0.0,0.00,2.0,903882.34,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,1127567.71,0.0,0.0,0.0,5088.05,0,0,0.0,0.00,0,5088.05
8,998000000245,Time Deposits,287050.00,1,0,0,2.0,41473.33,0.0,0.00,6.0,516581.66,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,239077.85,0.0,0.00,797132.84,0.0,0.0,0.0,2367.17,1,1,0.0,8.77,0,2127.17
9,998000000262,Time Deposits,762084.97,4,0,0,3.0,125762.58,0.0,0.00,4.0,2130590.11,0.0,0.0,1.0,180316.12,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,227326.09,1.0,126526.97,2790521.87,0.0,0.0,0.0,8324.88,0,0,96000.0,0.00,0,7884.88

In [88]:
unique_cifno_count = final_TD_df['CIFNO'].nunique()

if unique_cifno_count == len(final_TD_df):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

### Pawning

In [89]:
paw_df = df1[(df1['PRODUCT_DESC'] == 'Pawning')]

In [90]:
paw_df['DPD_LAST_6_MONTH'].value_counts()

0.0      107173
1.0          78
5.0          49
8.0          46
4.0          41
6.0          30
14.0         30
7.0          27
12.0         23
11.0         23
13.0         20
22.0         16
27.0         16
26.0         15
36.0         12
35.0         11
41.0         10
55.0         10
57.0          9
18.0          8
19.0          8
34.0          8
32.0          8
49.0          7
53.0          6
54.0          5
40.0          5
43.0          3
56.0          3
39.0          3
50.0          3
42.0          2
132.0         2
25.0          2
60.0          2
375.0         1
200.0         1
31.0          1
3.0           1
127.0         1
62.0          1
88.0          1
123.0         1
167.0         1
141.0         1
24.0          1
Name: DPD_LAST_6_MONTH, dtype: int64

In [91]:
paw_df.shape

(107725, 52)

In [92]:
paw_df1=paw_df[['CIFNO',  'PRODUCT_DESC',  'BAL_OS',
        'REGION_CD', 'ACCOUNT_JOINT','DPD_LAST_6_MONTH']]

In [93]:
pa_df = paw_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
                                                                            'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})
pa_df2=pa_df.sort_values(by=['BAL_OS',"REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"],ascending=False)
pa_df3=pa_df2.groupby('CIFNO').first().reset_index()
pa_df3.head()

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\795744029.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  pa_df = paw_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
C:\Users\15694\AppData\Local\Temp\ipykernel_12844\795744029.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})

     CIFNO PRODUCT_DESC    BAL_OS  REGION_CD  ACCOUNT_JOINT  DPD_LAST_6_MONTH
0  1000564      Pawning  738614.0          1              0               0.0
1  1000566      Pawning   81317.0          1              0               0.0
2  1000589      Pawning   95000.0          6              0               0.0
3  1000624      Pawning  563000.0          3              0               0.0
4  1000635      Pawning   69705.0          1              0               0.0

In [94]:
pa_df3.shape

(81307, 6)

In [95]:
unique_cifno_count_pa = pa_df3['CIFNO'].nunique()

if unique_cifno_count_pa == len(pa_df3):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [96]:
paw_df2=paw_df[[
"CIFNO",'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS',
       'SIX_MONTH_BAL_OS_SAVINGS', 'NO_ACCOUNTS_CURRENT',
       'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD', 'SIX_MONTH_BAL_OS_FD',
       'NO_ACCOUNTS_HOUSING', 'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM',
       'SIX_MONTH_BAL_OS_TERM', 'NO_ACCOUNTS_LEASING',
       'SIX_MONTH_BAL_OS_LEASING', 'NO_ACCOUNTS_PAWNING',
       'SIX_MONTH_BAL_OS_PAWNING', 'NO_ACCOUNTS_PERSONAL',
       'SIX_MONTH_BAL_OS_PERSONAL', 'NO_ACCOUNTS_SHORT_TERM',
       'SIX_MONTH_BAL_OS_SHORT_TERM', 'NO_ACCOUNTS_STAFF',
       'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE', 'SIX_MONTH_BAL_OS_TRADE',
       'NO_ACCOUNTS_DEVELOPMENT', 'SIX_MONTH_BAL_OS_DEVELOPMENT',
       'NO_ACCOUNTS_REFINANCE', 'SIX_MONTH_BAL_OS_REFINANCE',
       'NO_ACCOUNTS_CARD', 'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD',
       'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN',
       'CURRENT_AMOUNT_UNDER_LIEN', 'SAVINGS_AMOUNT_UNDER_LIEN',
       'CUSTOMER_PROFITABILITY', 'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS',
       'DEBIT_CARD_USAGE', 'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII'
       ]]

In [97]:
dpaw=paw_df2.groupby('CIFNO').first().reset_index()

In [98]:
dpaw.shape

(81307, 43)

In [99]:
final_pa_df=pd.merge(pa_df3, dpaw, on='CIFNO', how='left')

In [100]:
final_pa_df.rename(columns={'DPD_LAST_6_MONTH': 'DPD_LAST_6_MONTH_PAWNING'}, inplace=True)

In [101]:
final_pa_df.shape

(81307, 48)

In [102]:
final_pa_df.head()

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH_PAWNING,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,1000564,Pawning,738614.0,1,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1002159.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1002159.20,0.0,0.0,0.0,4662.23,0,0,0.0,0.00,0,4662.23
1,1000566,Pawning,81317.0,1,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,159667.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,159667.20,0.0,0.0,0.0,306.27,0,0,0.0,0.00,0,306.27
2,1000589,Pawning,95000.0,6,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,95000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95000.00,0.0,0.0,0.0,150.89,0,0,0.0,0.00,0,150.89
3,1000624,Pawning,563000.0,3,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1318937.32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1318937.32,0.0,0.0,0.0,7327.34,0,0,0.0,0.00,0,7327.34
4,1000635,Pawning,69705.0,1,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1033819.32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1033819.32,0.0,0.0,0.0,5848.52,0,0,0.0,1896.95,0,5848.52

In [103]:
unique_cifno_count = final_pa_df['CIFNO'].nunique()

if unique_cifno_count == len(final_pa_df):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

### Credit card

In [104]:
credit_df = df1[(df1['PRODUCT_DESC'] == 'Credit Card')]

In [105]:
credit_df['DPD_LAST_6_MONTH'].value_counts()

0.0       50017
6.0         124
24.0         18
10.0         17
36.0         15
16.0         10
126.0         3
65.0          3
155.0         2
58.0          2
44.0          1
247.0         1
93.0          1
218.0         1
1556.0        1
513.0         1
360.0         1
85.0          1
185.0         1
674.0         1
227.0         1
401.0         1
1395.0        1
422.0         1
268.0         1
1312.0        1
Name: DPD_LAST_6_MONTH, dtype: int64

In [106]:
credit_df.shape

(50227, 52)

In [107]:
CR_df1=credit_df[['CIFNO',  'PRODUCT_DESC',  'BAL_OS',
        'REGION_CD', 'ACCOUNT_JOINT','DPD_LAST_6_MONTH']]

In [108]:
CRE_df = CR_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
                                                                            'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})
CRE_df2=CRE_df.sort_values(by=['BAL_OS',"REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"],ascending=False)
CRE_df3=CRE_df2.groupby('CIFNO').first().reset_index()
CRE_df3.head()

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\3152489748.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  CRE_df = CR_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
C:\Users\15694\AppData\Local\Temp\ipykernel_12844\3152489748.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH
0,4157380000540004,Credit Card,-3204.85,1,0,0.0
1,4157380000662014,Credit Card,18090.57,3,0,0.0
2,4157380000672005,Credit Card,10441.41,1,0,0.0
3,4157380001111003,Credit Card,423169.35,4,0,0.0
4,4157380001688000,Credit Card,18620.32,3,0,0.0

In [109]:
CRE_df3.shape

(49383, 6)

In [110]:
unique_cifno_count_CR = CRE_df3['CIFNO'].nunique()

if unique_cifno_count_CR == len(CRE_df3):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [111]:
CR_df2=credit_df[[
"CIFNO",'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS',
       'SIX_MONTH_BAL_OS_SAVINGS', 'NO_ACCOUNTS_CURRENT',
       'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD', 'SIX_MONTH_BAL_OS_FD',
       'NO_ACCOUNTS_HOUSING', 'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM',
       'SIX_MONTH_BAL_OS_TERM', 'NO_ACCOUNTS_LEASING',
       'SIX_MONTH_BAL_OS_LEASING', 'NO_ACCOUNTS_PAWNING',
       'SIX_MONTH_BAL_OS_PAWNING', 'NO_ACCOUNTS_PERSONAL',
       'SIX_MONTH_BAL_OS_PERSONAL', 'NO_ACCOUNTS_SHORT_TERM',
       'SIX_MONTH_BAL_OS_SHORT_TERM', 'NO_ACCOUNTS_STAFF',
       'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE', 'SIX_MONTH_BAL_OS_TRADE',
       'NO_ACCOUNTS_DEVELOPMENT', 'SIX_MONTH_BAL_OS_DEVELOPMENT',
       'NO_ACCOUNTS_REFINANCE', 'SIX_MONTH_BAL_OS_REFINANCE',
       'NO_ACCOUNTS_CARD', 'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD',
       'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN',
       'CURRENT_AMOUNT_UNDER_LIEN', 'SAVINGS_AMOUNT_UNDER_LIEN',
       'CUSTOMER_PROFITABILITY', 'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS',
       'DEBIT_CARD_USAGE', 'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII',
       ]]

In [112]:
dCR=CR_df2.groupby('CIFNO').first().reset_index()

In [113]:
dCR.shape

(49383, 43)

In [114]:
final_CR_df=pd.merge(CRE_df3, dCR, on='CIFNO', how='left')

In [115]:
final_CR_df.rename(columns={'DPD_LAST_6_MONTH': 'DPD_LAST_6_MONTH_CREDIT_CARD'}, inplace=True)

In [116]:
final_CR_df.shape

(49383, 48)

In [117]:
final_CR_df.head()

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH_CREDIT_CARD,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,4157380000540004,Credit Card,-3204.85,1,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1396.41,0.0,0.0,1396.41,0.0,0.0,0.0,38.00,0,0,0.0,0.0,0,38.00
1,4157380000662014,Credit Card,18090.57,3,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7771.99,0.0,0.0,7771.99,0.0,0.0,0.0,-156.35,0,0,0.0,0.0,0,-156.35
2,4157380000672005,Credit Card,10441.41,1,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,18329.51,0.0,0.0,18329.51,0.0,0.0,0.0,81.43,0,0,0.0,0.0,0,81.43
3,4157380001111003,Credit Card,423169.35,4,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,403443.31,0.0,0.0,403443.31,0.0,0.0,0.0,9322.00,0,0,0.0,0.0,0,6155.30
4,4157380001688000,Credit Card,18620.32,3,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,17490.17,0.0,0.0,17490.17,0.0,0.0,0.0,3533.90,0,0,0.0,0.0,0,283.90

In [118]:
unique_cifno_count = final_CR_df['CIFNO'].nunique()

if unique_cifno_count == len(final_CR_df):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

### Current

In [119]:
Current_df = df1[(df1['PRODUCT_DESC'] == 'Current')]

In [120]:
Current_df.shape

(32968, 52)

In [121]:
Current_df['DPD_LAST_6_MONTH'].value_counts()

0.0       32639
31.0         46
2.0          38
1.0          31
3.0          23
61.0         18
6.0          16
9.0          13
8.0           9
151.0         6
7.0           6
92.0          6
120.0         6
28.0          5
10.0          5
23.0          5
14.0          4
273.0         4
29.0          4
35.0          3
38.0          3
24.0          3
20.0          3
17.0          3
243.0         3
37.0          3
13.0          2
212.0         2
51.0          2
62.0          2
45.0          2
4.0           2
21.0          2
152.0         2
16.0          2
79.0          2
1959.0        1
154.0         1
59.0          1
98.0          1
2085.0        1
1856.0        1
127.0         1
244.0         1
55.0          1
365.0         1
119.0         1
15.0          1
191.0         1
68.0          1
90.0          1
447.0         1
638.0         1
84.0          1
213.0         1
40.0          1
50.0          1
335.0         1
516.0         1
1102.0        1
121.0         1
430.0         1
69.0          1
5489.0        1
86.0          1
182.0         1
183.0         1
426.0         1
846.0         1
1310.0        1
72.0          1
32.0          1
132.0         1
141.0         1
364.0         1
52.0          1
304.0         1
701.0         1
58.0          1
Name: DPD_LAST_6_MONTH, dtype: int64

In [122]:
Cur_df1=Current_df[["CIFNO",'PRODUCT_DESC',"BAL_OS","REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"]]

In [123]:
CRR_df = Cur_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
                                                                            'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})
CRR_df2=CRR_df.sort_values(by=['BAL_OS',"REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"],ascending=False)
CRR_df3=CRR_df2.groupby('CIFNO').first().reset_index()
CRR_df3.head()

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\202111219.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  CRR_df = Cur_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
C:\Users\15694\AppData\Local\Temp\ipykernel_12844\202111219.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH
0,998000000001,Current,41851.43,1,0,0.0
1,998000000131,Current,5871.53,1,0,0.0
2,998000000327,Current,21771.00,1,0,0.0
3,998000000352,Current,0.00,1,0,0.0
4,998000000379,Current,516308.90,1,1,0.0

In [124]:
CRR_df3.shape

(31389, 6)

In [125]:
unique_cifno_count_CUR = CRR_df3['CIFNO'].nunique()

if unique_cifno_count_CUR == len(CRR_df3):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [126]:
Cur_df2=Current_df[[
"CIFNO",'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS',
       'SIX_MONTH_BAL_OS_SAVINGS', 'NO_ACCOUNTS_CURRENT',
       'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD', 'SIX_MONTH_BAL_OS_FD',
       'NO_ACCOUNTS_HOUSING', 'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM',
       'SIX_MONTH_BAL_OS_TERM', 'NO_ACCOUNTS_LEASING',
       'SIX_MONTH_BAL_OS_LEASING', 'NO_ACCOUNTS_PAWNING',
       'SIX_MONTH_BAL_OS_PAWNING', 'NO_ACCOUNTS_PERSONAL',
       'SIX_MONTH_BAL_OS_PERSONAL', 'NO_ACCOUNTS_SHORT_TERM',
       'SIX_MONTH_BAL_OS_SHORT_TERM', 'NO_ACCOUNTS_STAFF',
       'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE', 'SIX_MONTH_BAL_OS_TRADE',
       'NO_ACCOUNTS_DEVELOPMENT', 'SIX_MONTH_BAL_OS_DEVELOPMENT',
       'NO_ACCOUNTS_REFINANCE', 'SIX_MONTH_BAL_OS_REFINANCE',
       'NO_ACCOUNTS_CARD', 'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD',
       'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN',
       'CURRENT_AMOUNT_UNDER_LIEN', 'SAVINGS_AMOUNT_UNDER_LIEN',
       'CUSTOMER_PROFITABILITY', 'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS',
       'DEBIT_CARD_USAGE', 'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII'
       ]]

In [127]:
dCUR=Cur_df2.groupby('CIFNO').first().reset_index()

In [128]:
dCUR.shape

(31389, 43)

In [129]:
final_CRR_df=pd.merge(CRR_df3, dCUR, on='CIFNO', how='left')

In [130]:
final_CRR_df.rename(columns={'DPD_LAST_6_MONTH': 'DPD_LAST_6_MONTH_CURRENT'}, inplace=True)

In [131]:
final_CRR_df.head()

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH_CURRENT,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,998000000001,Current,41851.43,1,0,0.0,1,5.0,31359.30,36.0,44005.21,0.0,0.00,0.0,0.0,0.0,0.0,5.0,3952559.03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,4027923.54,0.0,799625.58,0.0,40560.33,0,0,0.0,0.00,0,18935.33
1,998000000131,Current,5871.53,1,0,0.0,0,3.0,206569.08,1.0,158171.26,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,364740.34,0.0,0.00,0.0,339.21,1,0,0.0,0.00,0,254.21
2,998000000327,Current,21771.00,1,0,0.0,0,1.0,93342.05,1.0,23408.38,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5982.24,0.0,0.0,122732.67,0.0,0.00,0.0,3026.04,1,0,2900.0,8444.54,0,451.04
3,998000000352,Current,0.00,1,0,0.0,0,3.0,817143.17,1.0,0.00,5.0,20498550.21,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11600000.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,59985.57,0.0,0.0,32975678.95,0.0,0.00,0.0,-123651.75,1,1,100000.0,150799.00,0,-123746.75
4,998000000379,Current,516308.90,1,1,0.0,0,0.0,0.00,1.0,738818.15,4.0,1442411.72,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,2181229.87,0.0,0.00,0.0,8589.17,1,0,0.0,0.00,0,8589.17

In [132]:
final_CRR_df.shape

(31389, 48)

In [133]:
unique_cifno_count = final_CRR_df['CIFNO'].nunique()

if unique_cifno_count == len(final_CRR_df):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

### Lease

In [134]:
Lease_df = df1[(df1['PRODUCT_DESC'] == 'Lease')]

In [135]:
Lease_df.shape

(7088, 52)

In [136]:
Lease_df['DPD_LAST_6_MONTH'].value_counts()

0.0       5470
3.0         83
2.0         81
1.0         74
4.0         58
6.0         55
7.0         55
5.0         53
9.0         51
8.0         51
31.0        44
12.0        42
13.0        41
14.0        37
15.0        37
10.0        35
16.0        32
18.0        31
11.0        30
24.0        30
21.0        28
22.0        28
23.0        28
19.0        28
20.0        26
32.0        25
38.0        22
43.0        21
26.0        20
17.0        20
33.0        20
36.0        20
29.0        20
42.0        19
39.0        19
48.0        18
37.0        18
30.0        18
28.0        18
25.0        17
34.0        17
44.0        17
40.0        17
35.0        14
49.0        14
27.0        14
41.0        12
45.0        12
47.0        11
46.0         9
53.0         9
50.0         8
52.0         7
56.0         7
51.0         7
59.0         7
54.0         6
58.0         5
55.0         5
60.0         4
63.0         3
82.0         3
57.0         3
71.0         3
92.0         2
130.0        2
62.0         2
84.0         2
68.0         2
129.0        2
76.0         2
85.0         2
255.0        1
73.0         1
133.0        1
120.0        1
195.0        1
64.0         1
96.0         1
118.0        1
236.0        1
160.0        1
70.0         1
77.0         1
144.0        1
106.0        1
74.0         1
72.0         1
142.0        1
126.0        1
95.0         1
301.0        1
148.0        1
112.0        1
124.0        1
132.0        1
314.0        1
127.0        1
495.0        1
379.0        1
61.0         1
1290.0       1
427.0        1
174.0        1
158.0        1
67.0         1
111.0        1
Name: DPD_LAST_6_MONTH, dtype: int64

In [137]:
lease_df1=Lease_df[["CIFNO",'PRODUCT_DESC',"BAL_OS","REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"]]

In [138]:
ls_df = lease_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
                                                                            'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})
ls_df2=ls_df.sort_values(by=['BAL_OS',"REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"],ascending=False)
ls_df3=ls_df2.groupby('CIFNO').first().reset_index()
ls_df3.head()

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\2536020537.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  ls_df = lease_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
C:\Users\15694\AppData\Local\Temp\ipykernel_12844\2536020537.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH
0,998000001009,Lease,3269006.83,10,0,0.0
1,998000002768,Lease,3290901.22,7,0,0.0
2,998000007683,Lease,6338544.70,8,0,14.0
3,998000017154,Lease,2873291.34,1,0,0.0
4,998000019202,Lease,7417046.96,1,0,0.0

In [139]:
ls_df3.shape

(6580, 6)

In [140]:
unique_cifno_count_ls = ls_df3['CIFNO'].nunique()

if unique_cifno_count_ls == len(ls_df3):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [141]:
lease_df2=Lease_df[[
"CIFNO",'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS',
       'SIX_MONTH_BAL_OS_SAVINGS', 'NO_ACCOUNTS_CURRENT',
       'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD', 'SIX_MONTH_BAL_OS_FD',
       'NO_ACCOUNTS_HOUSING', 'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM',
       'SIX_MONTH_BAL_OS_TERM', 'NO_ACCOUNTS_LEASING',
       'SIX_MONTH_BAL_OS_LEASING', 'NO_ACCOUNTS_PAWNING',
       'SIX_MONTH_BAL_OS_PAWNING', 'NO_ACCOUNTS_PERSONAL',
       'SIX_MONTH_BAL_OS_PERSONAL', 'NO_ACCOUNTS_SHORT_TERM',
       'SIX_MONTH_BAL_OS_SHORT_TERM', 'NO_ACCOUNTS_STAFF',
       'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE', 'SIX_MONTH_BAL_OS_TRADE',
       'NO_ACCOUNTS_DEVELOPMENT', 'SIX_MONTH_BAL_OS_DEVELOPMENT',
       'NO_ACCOUNTS_REFINANCE', 'SIX_MONTH_BAL_OS_REFINANCE',
       'NO_ACCOUNTS_CARD', 'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD',
       'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN',
       'CURRENT_AMOUNT_UNDER_LIEN', 'SAVINGS_AMOUNT_UNDER_LIEN',
       'CUSTOMER_PROFITABILITY', 'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS',
       'DEBIT_CARD_USAGE', 'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII'
       ]]

In [142]:
dls=lease_df2.groupby('CIFNO').first().reset_index()

In [143]:
dls.shape

(6580, 43)

In [144]:
final_ls_df=pd.merge(ls_df3, dls, on='CIFNO', how='left')

In [145]:
final_ls_df.rename(columns={'DPD_LAST_6_MONTH': 'DPD_LAST_6_MONTH_LEASE'}, inplace=True)

In [146]:
final_ls_df.shape

(6580, 48)

In [147]:
final_ls_df.head()

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH_LEASE,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,998000001009,Lease,3269006.83,10,0,0.0,0,4.0,689788.75,0.0,0.00,3.0,819732.71,0.0,0.00,1.0,13739494.65,4.0,9661130.11,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,2.491015e+07,30000.0,0.0,0.0,87094.26,0,0,4170.29,0.0,0,80394.26
1,998000002768,Lease,3290901.22,7,0,0.0,0,2.0,1763232.03,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,1.0,3322383.38,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,5.085615e+06,0.0,0.0,0.0,20344.06,0,0,0.00,0.0,0,20324.06
2,998000007683,Lease,6338544.70,8,0,14.0,0,2.0,8035.76,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,1.0,6536522.08,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,550454.56,0.0,0.00,7.095012e+06,0.0,0.0,0.0,9318.88,0,0,0.00,10100.0,0,9298.88
3,998000017154,Lease,2873291.34,1,0,0.0,0,2.0,71633.09,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,1.0,1918426.59,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,1.990060e+06,0.0,0.0,0.0,15839.24,0,1,30000.00,0.0,0,15809.24
4,998000019202,Lease,7417046.96,1,0,0.0,1,11.0,1777945.80,1.0,1053753.43,7.0,25948198.73,2.0,89343824.44,3.0,1467051.77,3.0,9546103.71,0.0,0.0,1.0,13042975.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44690.14,2.0,6739736.78,1.489643e+08,0.0,245983.3,0.0,-158939.06,1,1,0.00,70364.2,0,-176739.06

In [148]:
unique_cifno_count = final_ls_df['CIFNO'].nunique()

if unique_cifno_count == len(final_ls_df):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

### OVERDRAFT

In [149]:
OD_df = df1[(df1['PRODUCT_DESC'] == 'Overdraft')]

In [150]:
OD_df.shape

(4637, 52)

In [151]:
OD_df['DPD_LAST_6_MONTH'].value_counts()

0.0       4204
1.0         73
2.0         52
31.0        34
3.0         25
9.0         24
7.0         19
6.0         19
10.0        18
16.0        10
22.0         8
13.0         8
14.0         7
61.0         7
20.0         6
30.0         5
8.0          5
62.0         5
5.0          4
21.0         4
29.0         4
34.0         4
15.0         4
17.0         4
45.0         3
51.0         3
37.0         3
120.0        3
11.0         3
32.0         3
426.0        3
52.0         3
335.0        3
151.0        3
4.0          2
94.0         2
38.0         2
92.0         2
41.0         2
28.0         2
42.0         2
65.0         2
24.0         2
23.0         2
26.0         1
365.0        1
217.0        1
44.0         1
121.0        1
430.0        1
25.0         1
43.0         1
55.0         1
141.0        1
71.0         1
212.0        1
108.0        1
66.0         1
419.0        1
50.0         1
243.0        1
33.0         1
36.0         1
54.0         1
64.0         1
457.0        1
35.0         1
266.0        1
1097.0       1
517.0        1
56.0         1
304.0        1
76.0         1
135.0        1
78.0         1
1003.0       1
72.0         1
416.0        1
Name: DPD_LAST_6_MONTH, dtype: int64

In [152]:
OD_df1=OD_df[["CIFNO",'PRODUCT_DESC',"BAL_OS","REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"]]

In [153]:
od_df = OD_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
                                                                    'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})
od_df2=od_df.sort_values(by=['BAL_OS',"REGION_CD",'ACCOUNT_JOINT',"DPD_LAST_6_MONTH"],ascending=False)
od_df3=od_df2.groupby('CIFNO').first().reset_index()
od_df3.head()

C:\Users\15694\AppData\Local\Temp\ipykernel_12844\3969065006.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  od_df = OD_df1.groupby(['CIFNO','PRODUCT_DESC'],as_index=False).aggregate({'BAL_OS':'sum',"REGION_CD":lambda x: mode(x)[0][0],
C:\Users\15694\AppData\Local\Temp\ipykernel_12844\3969065006.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  'ACCOUNT_JOINT':lambda x: mode(x)[0][0],"DPD_LAST_6_MONTH":'max'})

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH
0,998000000347,Overdraft,7.092252e+05,1,0,0.0
1,998000000722,Overdraft,1.091640e+08,1,0,0.0
2,998000000790,Overdraft,1.500000e+04,10,0,0.0
3,998000000848,Overdraft,1.280210e+03,98,0,0.0
4,998000001943,Overdraft,9.994368e+05,1,0,0.0

In [154]:
od_df3.shape

(4555, 6)

In [155]:
unique_cifno_count_od = od_df3['CIFNO'].nunique()

if unique_cifno_count_od == len(od_df3):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [156]:
OD_df2=OD_df[[
"CIFNO",'NPA_FLAG', 'NO_ACCOUNTS_SAVINGS',
       'SIX_MONTH_BAL_OS_SAVINGS', 'NO_ACCOUNTS_CURRENT',
       'SIX_MONTH_BAL_OS_CURRENT', 'NO_ACCOUNTS_FD', 'SIX_MONTH_BAL_OS_FD',
       'NO_ACCOUNTS_HOUSING', 'SIX_MONTH_BAL_OS_HOUSING', 'NO_ACCOUNTS_TERM',
       'SIX_MONTH_BAL_OS_TERM', 'NO_ACCOUNTS_LEASING',
       'SIX_MONTH_BAL_OS_LEASING', 'NO_ACCOUNTS_PAWNING',
       'SIX_MONTH_BAL_OS_PAWNING', 'NO_ACCOUNTS_PERSONAL',
       'SIX_MONTH_BAL_OS_PERSONAL', 'NO_ACCOUNTS_SHORT_TERM',
       'SIX_MONTH_BAL_OS_SHORT_TERM', 'NO_ACCOUNTS_STAFF',
       'SIX_MONTH_BAL_OS_STAFF', 'NO_ACCOUNTS_TRADE', 'SIX_MONTH_BAL_OS_TRADE',
       'NO_ACCOUNTS_DEVELOPMENT', 'SIX_MONTH_BAL_OS_DEVELOPMENT',
       'NO_ACCOUNTS_REFINANCE', 'SIX_MONTH_BAL_OS_REFINANCE',
       'NO_ACCOUNTS_CARD', 'SIX_MONTH_BAL_OS_CARD', 'NO_ACCOUNTS_OD',
       'SIX_MONTH_BAL_OS_OD', 'TOTAL_AVG_BAL', 'FD_AMOUNT_UNDER_LIEN',
       'CURRENT_AMOUNT_UNDER_LIEN', 'SAVINGS_AMOUNT_UNDER_LIEN',
       'CUSTOMER_PROFITABILITY', 'E_BANKING_ACCOUNTS', 'SOLO_ACCOUNTS',
       'DEBIT_CARD_USAGE', 'CREDIT_CARD_USAGE', 'PAYFAST_ACCOUNT', 'NII'
       ]]

In [157]:
dOD=OD_df2.groupby('CIFNO').first().reset_index()

In [158]:
dOD.shape

(4555, 43)

In [159]:
final_od_df=pd.merge(od_df3, dOD, on='CIFNO', how='left')

In [160]:
final_od_df.rename(columns={'DPD_LAST_6_MONTH': 'DPD_LAST_6_MONTH_OD'}, inplace=True)

In [161]:
final_od_df.shape

(4555, 48)

In [162]:
final_od_df.head()

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH_OD,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,998000000347,Overdraft,7.092252e+05,1,0,0.0,0,10.0,685460.32,1.0,0.00,4.0,1551585.93,5.0,2436564.48,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0,6.978753e+05,5.371486e+06,0.0,0.0,9128.63,2837.15,1,1,20000.0,0.00,0,2722.15
1,998000000722,Overdraft,1.091640e+08,1,0,0.0,1,2.0,237067.64,2.0,0.00,0.0,0.00,0.0,0.00,1.0,23603663.98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2377236.82,2.0,2.506932e+08,2.769111e+08,0.0,0.0,0.00,708589.76,1,0,0.0,690073.20,0,708589.76
2,998000000790,Overdraft,1.500000e+04,10,0,0.0,0,4.0,13300.77,0.0,0.00,0.0,305376.34,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,13222834.79,0.0,0.0,0.0,0.0,0.0,0.0,2.0,498510.80,1.0,2.797460e+05,1.431977e+07,0.0,0.0,0.00,-135746.83,1,1,136800.0,37833.48,0,-135926.83
3,998000000848,Overdraft,1.280210e+03,98,0,0.0,0,5.0,2054202.39,1.0,5196.79,3.0,90000000.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,383998.96,1.0,3.052800e+02,9.244370e+07,0.0,0.0,0.00,41073.91,0,0,0.0,37837.58,0,37716.99
4,998000001943,Overdraft,9.994368e+05,1,0,0.0,0,4.0,38572.62,0.0,0.00,3.0,3662365.59,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,23077509.79,0.0,0.0,0.0,0.0,0.0,0.0,2.0,326814.89,1.0,4.550480e+05,2.756031e+07,0.0,0.0,0.00,-186173.74,1,1,61400.0,35579.03,0,-186483.74

In [163]:
unique_cifno_count = final_od_df['CIFNO'].nunique()

if unique_cifno_count == len(final_od_df):
    print("All CIFNO values are unique.")
else:
    print("There are duplicate CIFNO values.")

All CIFNO values are unique.

In [164]:
full_df = pd.concat([final_loan_df, final_sav_df,final_TD_df,final_pa_df,final_CR_df,final_CRR_df,final_ls_df,final_od_df],
                    axis=0, ignore_index=True)

In [165]:
full_df.shape

(830689, 53)

In [166]:
full_df.head()

,CIFNO,PRODUCT_DESC,BAL_OS,REGION_CD,ACCOUNT_JOINT,DPD_LAST_6_MONTH_LOAN,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII,DPD_LAST_6_MONTH_PAWNING,DPD_LAST_6_MONTH_CREDIT_CARD,DPD_LAST_6_MONTH_CURRENT,DPD_LAST_6_MONTH_LEASE,DPD_LAST_6_MONTH_OD
0,998000000102,Loan,129609.51,3,0,0.0,0,4.0,699504.75,0.0,0.0,3.0,378962.46,0.0,0.0,1.0,41495.97,0.0,0.0,0.0,0.0,2.0,2005943.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,20623.80,0.0,0.00,3146530.15,0.0,0.0,0.0,13770.79,1,1,200131.0,61300.72,0,12645.79,NaN,NaN,NaN,NaN,NaN
1,998000000173,Loan,1637529.58,10,0,0.0,0,3.0,53083.62,0.0,0.0,1.0,2838709.68,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,1751763.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,4643556.31,0.0,0.0,0.0,1560.99,1,0,0.0,0.00,0,1560.99,NaN,NaN,NaN,NaN,NaN
2,998000000262,Loan,157280.00,8,0,0.0,0,3.0,125762.58,0.0,0.0,4.0,2130590.11,0.0,0.0,1.0,180316.12,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,227326.09,1.0,126526.97,2790521.87,0.0,0.0,0.0,8324.88,0,0,96000.0,0.00,0,7884.88,NaN,NaN,NaN,NaN,NaN
3,998000001044,Loan,1105600.00,2,1,0.0,0,1.0,5089.71,0.0,0.0,2.0,7822222.22,0.0,0.0,2.0,1550494.29,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,9377806.22,0.0,0.0,0.0,48863.78,0,0,0.0,0.00,0,48863.78,NaN,NaN,NaN,NaN,NaN
4,998000001498,Loan,3478692.89,3,0,0.0,1,2.0,427008.66,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,3800049.63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,4227058.29,0.0,0.0,0.0,11543.94,1,0,0.0,0.00,0,11483.94,NaN,NaN,NaN,NaN,NaN

In [167]:
full_df["DPD_LAST_6_MONTH_LOAN"].value_counts()

0.0       9713
4.0        211
7.0        166
2.0        105
17.0        73
8.0         63
5.0         61
12.0        60
34.0        58
6.0         57
3.0         56
37.0        54
32.0        47
9.0         46
27.0        41
10.0        38
11.0        36
22.0        35
14.0        32
23.0        32
1.0         32
38.0        31
13.0        30
36.0        29
15.0        28
47.0        27
35.0        25
20.0        25
42.0        24
19.0        24
40.0        23
33.0        23
26.0        22
39.0        21
16.0        21
31.0        20
24.0        20
52.0        20
21.0        19
18.0        18
30.0        16
29.0        14
50.0        14
44.0        14
43.0        12
28.0        12
55.0        12
46.0        12
49.0        11
25.0        11
48.0        11
45.0        10
41.0         9
51.0         9
462.0        8
56.0         7
69.0         6
57.0         5
63.0         5
53.0         5
65.0         5
61.0         5
93.0         4
73.0         4
68.0         4
122.0        3
54.0         3
72.0         3
59.0         3
70.0         3
81.0         3
102.0        3
434.0        2
461.0        2
112.0        2
407.0        2
87.0         2
86.0         2
130.0        2
311.0        2
58.0         2
466.0        2
341.0        2
60.0         2
126.0        2
64.0         2
76.0         2
352.0        2
290.0        1
484.0        1
99.0         1
250.0        1
142.0        1
319.0        1
150.0        1
379.0        1
262.0        1
358.0        1
486.0        1
492.0        1
80.0         1
170.0        1
165.0        1
96.0         1
147.0        1
417.0        1
85.0         1
443.0        1
638.0        1
385.0        1
338.0        1
244.0        1
77.0         1
216.0        1
857.0        1
197.0        1
402.0        1
277.0        1
116.0        1
109.0        1
432.0        1
90.0         1
159.0        1
431.0        1
100.0        1
163.0        1
106.0        1
97.0         1
145.0        1
433.0        1
394.0        1
375.0        1
118.0        1
238.0        1
391.0        1
134.0        1
429.0        1
127.0        1
380.0        1
62.0         1
488.0        1
132.0        1
101.0        1
164.0        1
168.0        1
416.0        1
280.0        1
272.0        1
310.0        1
340.0        1
141.0        1
336.0        1
377.0        1
219.0        1
125.0        1
89.0         1
152.0        1
430.0        1
161.0        1
318.0        1
240.0        1
401.0        1
235.0        1
501.0        1
400.0        1
369.0        1
148.0        1
103.0        1
149.0        1
75.0         1
573.0        1
78.0         1
193.0        1
169.0        1
153.0        1
189.0        1
420.0        1
372.0        1
1049.0       1
143.0        1
Name: DPD_LAST_6_MONTH_LOAN, dtype: int64

In [168]:
full_df["DPD_LAST_6_MONTH_PAWNING"].value_counts()

0.0      80790
1.0         76
5.0         47
8.0         42
4.0         39
14.0        29
6.0         25
7.0         23
11.0        23
12.0        22
13.0        20
27.0        16
22.0        16
26.0        13
36.0        11
41.0        10
35.0         9
18.0         8
32.0         8
19.0         8
34.0         8
49.0         7
57.0         7
53.0         6
54.0         5
55.0         5
40.0         4
50.0         3
56.0         3
39.0         3
43.0         3
60.0         2
25.0         2
132.0        2
42.0         2
200.0        1
31.0         1
127.0        1
141.0        1
375.0        1
167.0        1
62.0         1
123.0        1
88.0         1
24.0         1
Name: DPD_LAST_6_MONTH_PAWNING, dtype: int64

In [169]:
full_df["DPD_LAST_6_MONTH_CREDIT_CARD"].value_counts()

0.0       49173
6.0         124
24.0         18
10.0         17
36.0         15
16.0         10
126.0         3
65.0          3
58.0          2
155.0         2
218.0         1
93.0          1
247.0         1
401.0         1
422.0         1
227.0         1
1395.0        1
85.0          1
268.0         1
185.0         1
1556.0        1
44.0          1
1312.0        1
674.0         1
360.0         1
513.0         1
Name: DPD_LAST_6_MONTH_CREDIT_CARD, dtype: int64

In [170]:
full_df["DPD_LAST_6_MONTH_CURRENT"].value_counts()

0.0       31061
31.0         46
2.0          38
1.0          30
3.0          23
61.0         18
6.0          16
9.0          13
8.0           9
120.0         6
151.0         6
92.0          6
7.0           6
10.0          5
28.0          5
23.0          5
29.0          4
14.0          4
273.0         4
20.0          3
24.0          3
37.0          3
243.0         3
35.0          3
17.0          3
38.0          3
212.0         2
79.0          2
45.0          2
13.0          2
62.0          2
16.0          2
51.0          2
152.0         2
21.0          2
4.0           2
191.0         1
701.0         1
98.0          1
154.0         1
121.0         1
50.0          1
182.0         1
516.0         1
1310.0        1
68.0          1
141.0         1
846.0         1
1856.0        1
213.0         1
32.0          1
40.0          1
52.0          1
1102.0        1
183.0         1
244.0         1
59.0          1
430.0         1
304.0         1
447.0         1
132.0         1
119.0         1
15.0          1
72.0          1
335.0         1
364.0         1
638.0         1
84.0          1
55.0          1
58.0          1
5489.0        1
2085.0        1
127.0         1
86.0          1
426.0         1
365.0         1
90.0          1
1959.0        1
69.0          1
Name: DPD_LAST_6_MONTH_CURRENT, dtype: int64

In [171]:
full_df["DPD_LAST_6_MONTH_LEASE"].value_counts()

0.0       5055
3.0         80
2.0         74
1.0         73
4.0         57
6.0         53
7.0         52
5.0         51
9.0         50
8.0         50
31.0        38
13.0        37
12.0        37
15.0        36
10.0        34
14.0        34
16.0        29
24.0        29
11.0        29
18.0        28
22.0        26
23.0        26
21.0        26
19.0        25
20.0        25
32.0        22
33.0        20
38.0        20
26.0        20
36.0        19
43.0        19
39.0        19
17.0        19
29.0        19
48.0        18
30.0        18
37.0        17
42.0        17
34.0        17
44.0        17
28.0        16
25.0        15
49.0        14
35.0        14
40.0        14
27.0        13
41.0        12
45.0        12
53.0         9
46.0         9
50.0         8
47.0         8
59.0         7
52.0         6
51.0         6
54.0         6
56.0         6
55.0         5
58.0         5
60.0         4
57.0         3
71.0         3
82.0         3
129.0        2
68.0         2
130.0        2
62.0         2
92.0         2
236.0        1
95.0         1
160.0        1
314.0        1
195.0        1
126.0        1
120.0        1
74.0         1
144.0        1
85.0         1
77.0         1
72.0         1
255.0        1
111.0        1
70.0         1
132.0        1
84.0         1
106.0        1
76.0         1
142.0        1
124.0        1
112.0        1
301.0        1
158.0        1
73.0         1
96.0         1
148.0        1
118.0        1
1290.0       1
127.0        1
174.0        1
379.0        1
495.0        1
133.0        1
427.0        1
61.0         1
67.0         1
Name: DPD_LAST_6_MONTH_LEASE, dtype: int64

In [172]:
full_df["DPD_LAST_6_MONTH_OD"].value_counts()

0.0       4124
1.0         73
2.0         52
31.0        34
3.0         24
9.0         24
6.0         19
7.0         19
10.0        17
16.0        10
22.0         8
13.0         8
61.0         7
14.0         7
20.0         6
62.0         5
8.0          5
30.0         5
29.0         4
21.0         4
15.0         4
5.0          4
17.0         4
34.0         4
37.0         3
335.0        3
120.0        3
52.0         3
151.0        3
45.0         3
51.0         3
426.0        3
11.0         3
32.0         3
41.0         2
4.0          2
38.0         2
24.0         2
92.0         2
23.0         2
28.0         2
65.0         2
42.0         2
94.0         2
36.0         1
416.0        1
76.0         1
44.0         1
55.0         1
1097.0       1
365.0        1
121.0        1
1003.0       1
43.0         1
35.0         1
217.0        1
212.0        1
66.0         1
50.0         1
304.0        1
457.0        1
135.0        1
517.0        1
419.0        1
266.0        1
64.0         1
108.0        1
71.0         1
33.0         1
243.0        1
54.0         1
72.0         1
26.0         1
141.0        1
78.0         1
430.0        1
25.0         1
56.0         1
Name: DPD_LAST_6_MONTH_OD, dtype: int64

In [173]:
columns_to_drop = ['BAL_OS',"PRODUCT_DESC",
    "DPD_LAST_6_MONTH_LOAN",
    "DPD_LAST_6_MONTH_PAWNING",
    "DPD_LAST_6_MONTH_CREDIT_CARD",
    "DPD_LAST_6_MONTH_CURRENT",
    "DPD_LAST_6_MONTH_LEASE",
    "DPD_LAST_6_MONTH_OD"
]

In [174]:
full_df = full_df.drop(columns=columns_to_drop)

In [175]:
full_df.head()

,CIFNO,REGION_CD,ACCOUNT_JOINT,NPA_FLAG,NO_ACCOUNTS_SAVINGS,SIX_MONTH_BAL_OS_SAVINGS,NO_ACCOUNTS_CURRENT,SIX_MONTH_BAL_OS_CURRENT,NO_ACCOUNTS_FD,SIX_MONTH_BAL_OS_FD,NO_ACCOUNTS_HOUSING,SIX_MONTH_BAL_OS_HOUSING,NO_ACCOUNTS_TERM,SIX_MONTH_BAL_OS_TERM,NO_ACCOUNTS_LEASING,SIX_MONTH_BAL_OS_LEASING,NO_ACCOUNTS_PAWNING,SIX_MONTH_BAL_OS_PAWNING,NO_ACCOUNTS_PERSONAL,SIX_MONTH_BAL_OS_PERSONAL,NO_ACCOUNTS_SHORT_TERM,SIX_MONTH_BAL_OS_SHORT_TERM,NO_ACCOUNTS_STAFF,SIX_MONTH_BAL_OS_STAFF,NO_ACCOUNTS_TRADE,SIX_MONTH_BAL_OS_TRADE,NO_ACCOUNTS_DEVELOPMENT,SIX_MONTH_BAL_OS_DEVELOPMENT,NO_ACCOUNTS_REFINANCE,SIX_MONTH_BAL_OS_REFINANCE,NO_ACCOUNTS_CARD,SIX_MONTH_BAL_OS_CARD,NO_ACCOUNTS_OD,SIX_MONTH_BAL_OS_OD,TOTAL_AVG_BAL,FD_AMOUNT_UNDER_LIEN,CURRENT_AMOUNT_UNDER_LIEN,SAVINGS_AMOUNT_UNDER_LIEN,CUSTOMER_PROFITABILITY,E_BANKING_ACCOUNTS,SOLO_ACCOUNTS,DEBIT_CARD_USAGE,CREDIT_CARD_USAGE,PAYFAST_ACCOUNT,NII
0,998000000102,3,0,0,4.0,699504.75,0.0,0.0,3.0,378962.46,0.0,0.0,1.0,41495.97,0.0,0.0,0.0,0.0,2.0,2005943.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,20623.80,0.0,0.00,3146530.15,0.0,0.0,0.0,13770.79,1,1,200131.0,61300.72,0,12645.79
1,998000000173,10,0,0,3.0,53083.62,0.0,0.0,1.0,2838709.68,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,1751763.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,4643556.31,0.0,0.0,0.0,1560.99,1,0,0.0,0.00,0,1560.99
2,998000000262,8,0,0,3.0,125762.58,0.0,0.0,4.0,2130590.11,0.0,0.0,1.0,180316.12,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,227326.09,1.0,126526.97,2790521.87,0.0,0.0,0.0,8324.88,0,0,96000.0,0.00,0,7884.88
3,998000001044,2,1,0,1.0,5089.71,0.0,0.0,2.0,7822222.22,0.0,0.0,2.0,1550494.29,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,9377806.22,0.0,0.0,0.0,48863.78,0,0,0.0,0.00,0,48863.78
4,998000001498,3,0,1,2.0,427008.66,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,3800049.63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,4227058.29,0.0,0.0,0.0,11543.94,1,0,0.0,0.00,0,11483.94

In [176]:
full_df.isna().sum()

CIFNO                           0
REGION_CD                       0
ACCOUNT_JOINT                   0
NPA_FLAG                        0
NO_ACCOUNTS_SAVINGS             0
SIX_MONTH_BAL_OS_SAVINGS        0
NO_ACCOUNTS_CURRENT             0
SIX_MONTH_BAL_OS_CURRENT        0
NO_ACCOUNTS_FD                  0
SIX_MONTH_BAL_OS_FD             0
NO_ACCOUNTS_HOUSING             0
SIX_MONTH_BAL_OS_HOUSING        0
NO_ACCOUNTS_TERM                0
SIX_MONTH_BAL_OS_TERM           0
NO_ACCOUNTS_LEASING             0
SIX_MONTH_BAL_OS_LEASING        0
NO_ACCOUNTS_PAWNING             0
SIX_MONTH_BAL_OS_PAWNING        0
NO_ACCOUNTS_PERSONAL            0
SIX_MONTH_BAL_OS_PERSONAL       0
NO_ACCOUNTS_SHORT_TERM          0
SIX_MONTH_BAL_OS_SHORT_TERM     0
NO_ACCOUNTS_STAFF               0
SIX_MONTH_BAL_OS_STAFF          0
NO_ACCOUNTS_TRADE               0
SIX_MONTH_BAL_OS_TRADE          0
NO_ACCOUNTS_DEVELOPMENT         0
SIX_MONTH_BAL_OS_DEVELOPMENT    0
NO_ACCOUNTS_REFINANCE           0
SIX_MONTH_BAL_OS_REFINANCE      0
NO_ACCOUNTS_CARD                0
SIX_MONTH_BAL_OS_CARD           0
NO_ACCOUNTS_OD                  0
SIX_MONTH_BAL_OS_OD             0
TOTAL_AVG_BAL                   0
FD_AMOUNT_UNDER_LIEN            0
CURRENT_AMOUNT_UNDER_LIEN       0
SAVINGS_AMOUNT_UNDER_LIEN       0
CUSTOMER_PROFITABILITY          0
E_BANKING_ACCOUNTS              0
SOLO_ACCOUNTS                   0
DEBIT_CARD_USAGE                0
CREDIT_CARD_USAGE               0
PAYFAST_ACCOUNT                 0
NII                             0
dtype: int64

In [179]:
filepath=r"C://Users//15694//Desktop//Cross selling//code//Michelle//Total_unique_preprocess_data.csv"
full_df.to_csv(filepath, index=False)